### ISSUE TITLE
keyvalue error when trying to get output

### ISSUE THREAD

**Issue by SadafSafder23** [danforthcenter/plantcv#1001]
Hello, i am working on counting leave and measuring the angles of leaves, the following code i am using to measuring the segment path length.
```
labeled_img  = pcv.morphology.segment_path_length(segmented_img=segmented_img, 
                                                  objects=leaf_obj)

labeled_img = pcv.morphology.segment_euclidean_length(segmented_img=segmented_img, 
                                                      objects=leaf_obj)
```
the result is pretty much fine but when i am trying to insert the data into table using below code then `_keyerror_ `is occur

![image](https://user-images.githubusercontent.com/127180363/223984708-0850e93d-e6b2-4a3f-964c-f550a629fb18.png)
```

leaf_ids = np.vstack(pcv.outputs.observations['segment_path_length']['label'])

segment_path_length = np.vstack(pcv.outputs.observations['segment_path_length']['value'])
```
kindly help what is the reason behind it.

**Comment by HaleySchuhl** [comment]
Hi @SadafSafder23 ,

I think what you want is the following: 
```
pcv.outputs.observations['default']['segment_path_length']['label']

pcv.outputs.observations['default']['segment_path_length']['value']
```
All analysis functions have a `label` parameter which refers to the sample label. This allows for workflows where there are more than one object per image so that replicates are stored separately. 

You can also output all collected observations by using our [method](https://plantcv.readthedocs.io/en/latest/outputs/) `pcv.outputs.save_results(filename=args.result, outformat="json")` .  Hope this helps!

**Comment by SadafSafder23** [comment]
Thank you @HaleySchuhl, for your response, i want to save all output in a table format, that's why i am using `np.vstack` but this function is not worked for me.

**Comment by SadafSafder23** [comment]
Thank you @HaleySchuhl, it's worked for me.
