### ISSUE TITLE
dead plant values

### ISSUE THREAD

**Issue by Javi-Rop** [danforthcenter/plantcv#1203]
We are finding overestimated values when using the analyzeindex function, we have detected that it is because it does not use all the pixels chosen in the mask, analyzing the code of the function it is due to the conditional np.where(mask >0). This causes us problems when phenotyping plants that have dead zones, since we need to make an average in the entire area of the mask. Obtaining the wrong value for our type of assay gives us a power measured in dose-response curves that is higher than expected. My question is if we need some kind of correction to get the means of the indices if parts of the plant are giving 0

**Comment by Javi-Rop** [comment]
![img](https://github.com/danforthcenter/plantcv/assets/59958642/f9456493-d6e0-4fe4-a015-578f23bf97bd)

**Comment by nfahlgren** [comment]
Hi @Javi-Rop, the code `np.where(mask >0)` is intentional because one only wants to analyze the index values for the masked plant area and not the background.

Am I understanding your issue correctly, that your mask for the dead plants has undetected/missing parts? If that is the case you might be able to fill in missing areas with `pcv.fill_holes` or `pcv.closing`.

Note that in addition to filtering the index image on the masked area, we also have to exclude index values that are not finite values (`masked_array = masked_array[np.isfinite(masked_array)]`). It's common to get NaN, -Inf, and Inf values for indices for things like dead plant areas (e.g. when the index denominator is 0).

**Comment by Javi-Rop** [comment]
Hi @nfahlgren,

Thank you for your prompt response and for your suggerences, however our problem is diferent, since we are able to detect even the dead plants with our mask.

Nevertheless, there are some areas into the mask where the values are 0 (those areas corresponding with dead foliar plant tissues) and are not taking into account to calculate the mean of all index. Do you have any idea how can we solved this issue?

Thank you very much in advanced.

**Comment by nfahlgren** [comment]
0 values of the index are not removed, only NaN, Inf, and -Inf values are ignored. But those values cannot be included in the calculation of the mean, those are areas where the index cannot be calculated with a rational value.

**Comment by Javi-Rop** [comment]
Hi @nfahlgren,

Thank you for your prompt response

Thanks for your prompt response.It`s correct that 0 values are not removed, but these values are not included in the mean. In one of our test, we observed that the value of FvFm is 0.625 for a plant that at first glance is quite affected. When we saw this value, we proceeded to verify that the mask was generated correctly. Thus, we realize that the PlantCV function to analyze FvFm isn’t take into account the 0 values in order to calculate this mean. That is, despite our mask is correctly segmenting the image, the dead tissue (0 values) are avoiding in the FvFm calculation, obtaining FvFm higher tan expected, as you can see in the attached image.

![image](https://github.com/danforthcenter/plantcv/assets/59958642/b339872d-d3d4-4a74-ad7f-068e217340fb)

**Comment by nfahlgren** [comment]
Sorry, I misunderstood and thought you were using `pcv.hyperspectral.analyze_index`, but sounds like you're using `pcv.photosynthesis.analyze_fvfm`?

**Comment by Javi-Rop** [comment]
we use both, 
if we calculate the sum of the pixels of the histogram is less than the pixels of the mask.it's possible?

**Comment by nfahlgren** [comment]
For `analyze_index` the sum of the histogram will be less than the number of white pixels in the mask if any of the masked values are calculated as NaN or +/-Inf.

For `analyze_fvfm, the current formula is:
* Mask Fm and F0, setting the background to zero
* Calculate Fv (Fm - F0)
* Sometimes F0 is brighter than Fm, so set all negative numbers to 0
* Calculate Fv/Fm for all pixels in the mask
* Calculate summary stats and histogram data where Fv/Fm > 0 (because the background is zero)

For `analyze_index` I do not see a workaround other than setting non-numeric data to some constant value, but not sure that's ideal nor something that would work well across a wide range of indices - open to suggests though!

The `analyze_fvfm` formula probably causes bigger issues than `analyze_index` and I do not think it is as ideal as it could be. We completely redeveloped the `photosynthesis` submodule for the upcoming PlantCV4 release. The submodule can now do Fv/Fm, Fq'/Fm', NPQ, and some other features. The new Fv/Fm calculation looks like this:
* Mask the whole data array setting the background to NaN
* Calculate Fv/Fm
* Summarize where Fv/Fm > 0 (But I guess this condition doesn't need to be there since the background values are NaN)

Would you be interested in trying the PlantCV4 version? Broadly, PlantCV4 makes it easier to analyze multiple plant/objects - though the update for that for the photosynthesis tools is not quite merged in yet.

Staging for PlantCV4 is in this branch: https://github.com/danforthcenter/plantcv/tree/release-4.0, with this open update in the works for the photosynthesis tools: https://github.com/danforthcenter/plantcv/pull/1201. The live documentation for v4 is here: https://plantcv.readthedocs.io/en/release-4.0/

**Comment by Javi-Rop** [comment]
wow that's very good

Thank you for your prompt response, thank you for facilitating the work of many researchers and congratulations on the great work you are doing

all the best
