### ISSUE TITLE
Histogram plots not showing when developing workflow in Spyder

### ISSUE THREAD

**Issue by gustafmalone** [danforthcenter/plantcv#1365]
Hi everyone,

I'm learning PlantCV at the moment for a project, and have been working my way through the [Arabidopsis multi plant tutorial](https://plantcv.readthedocs.io/en/stable/tutorials/arabidopsis_multi_plant_tutorial/). I have copied the code in the tutorial exactly into Spyder, and nearly everything works as expected; the image is read properly, the various debug plots appear as expected in the "plots" panel of Spyder, and the output file with all the output data generates as expected in my working directory.

However, at `In <8>` in the tutorial, a histogram is generated using:

`hist = pcv.visualize.histogram(img=a, bins=25)`

For whatever reason, this does not appear in the "plots" panel in Spyder as I would expect. Instead, the following appears in Spyder's IPython console:

`alt.Chart(...)`

No other errors are generated.

I have tried changing the graphics backend in the Spyder preferences to each of the available options but this has not resolved the issue.

I understand it is recommended to develop workflows in a Jupyter notebook, and the histogram does generate as expected in Jupyter. However, I would personally prefer to continue developing my workflows in Spyder if possible, so I was wondering if anybody knows of anyway to get the histogram to appear there? I am running Spyder 5.4.3 in a PlantCV 4.0.1 environment in Conda on Windows 10.

Many thanks

**Comment by gustafmalone** [comment]
I have managed to find a workaround by simply outputting the histogram image to file.

`hist = pcv.visualize.histogram(img=a, bins=25)`
`pcv.print_image(hist, "./output/hist.png")`

It's a little annoying that I can't see it directly in the IDE but at least I can see histograms when developing my workflow now.

**Comment by nfahlgren** [comment]
Hi @gustafmalone, sorry for the delay. We don't use Spyder so it's not something we have tested. In PlantCV4 we replaced the plotting library plotnine with altair. By default altair produces charts in HTML and Spyder does not support displaying HTML: https://github.com/spyder-ide/spyder/issues/6200

Based on this documentation for altair (https://altair-viz.github.io/user_guide/display_frontends.html), I believe you can run the following to change the altair renderer to PNG, which I think Spyder should support:

```python
import altair as alt
alt.renderers.enable("png")
```

Then run PlantCV as normal and my assumption is it will display the charts as PNGs instead of HTML. Though note that they will not be interactive like they are as HTML.

**Comment by gustafmalone** [comment]
Thank you @nfahlgren, this has done the trick! The HTML functionality isn't something I need so this is perfect.
