### ISSUE TITLE
Use Raspberry pi camera

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#137]
Hi guys 
I would like to write a script that would periodically take a picture using the raspberry pi camera and afterward run a pipeline of it. The main goal is to find the mass of my top view plants. ( i am going to base myself just on the area of them, any other suggestions?)

Can i do this with the plantCV package? or should i be using something like raspistill or another serivce like motion?

Thanks in advance

**Comment by nfahlgren** [comment]
PlantCV does not have the tools to take the pictures themselves. I think we always use raspistill when we are using the Pi cameras. There are several things we do to automate imaging. The simplest method, if you have a small number of Pis is to use the `cron` scheduler: https://github.com/danforthcenter/outreach/blob/reu_2016/using_raspberry_pi_cameras.md. That just takes pictures on a schedule, so you would need to combine that with scheduled transfers from your Pi to a server, or to couple it with PlantCV directly on the Pi, but these functions can be done in cron as well. @jshoyer has a much better write up of this for his system: https://github.com/jshoyer/raspi-topdown-plant-imaging-12x.

If you need to control a lot of Pis, @calizarr has a system for doing this with `ansible`: https://github.com/calizarr/EPSCoR_Bramble_GH9C

**Comment by MjBordalo** [comment]
Thanks @nfahlgren I dont really need to have a scheduler either to control mutiple pi , but thanks for the tips. I Have another software managing my small greenhouse system that could call a script periodically that i guess that would thus call rapstil and afterwards PlantCV. lets see if ill manage that. Thanks

**Comment by MjBordalo** [comment]
Ok so now i suggest that in the docs you could have a section for the pi.Like installation and basic scripts. I see you use it a lot so it would be very nice.

**Comment by jshoyer** [comment]
Thanks for the suggestion @MjBordalo. An overview page on how to acquire good images for quantitative processing might be useful. Such a page could include links such as the ones Noah provided. It is hard, however, to offer general advice, because there are many different use cases.

I do not think that the PlantCV docs are a good place for a full-on tutorial on configuring Raspberry Pi imaging. Specific GitHub repositories and http://maker.danforthcenter.org (for example) are better places. Linking documentation pages too closely to a specific Raspberry Pi Camera version (or Lemnatec Scanalyzer, or DSLR, ...) could cause conceptual confusion. That said, feel free to take a stab at writing documentation based on your own experience and send a pull request for feedback.

Do have additional specific questions? Or are you satisfied with whatever bash or python scripts you have written/adapted?

**Comment by MjBordalo** [comment]
@jshoyer  maybe you are right about the documentation spot (not an expert here), but for example you Using PlantCV with Jupyter Notebooks section there.Why not to have a short one like that explaining hot o install it on the pi and how to do one or two things with the raspistill?

Sure i can share my experience.

I am happy :+1: ty

**Comment by jshoyer** [comment]
I think now that there might be some utility in enabling some functions for directly taking PiCam photos to PlantCV and/or providing more advice about using `picamera` to the PlantCV documentation.

I think this mostly because of the idea that a few of us have discussed for using PlantCV to automatically detect color standard objects, measure them, and iteratively improve image capture settings. Such code would use multiple ColorChecker patches, beyond what was done in pull request #45 (for issue #25).

I have always just used `raspistill`, but I have also always considered using the `picamera` module, mostly to capture the analog gain, digital gain, and awb (red, blue) gains, which I do not otherwise know how to save. I have not been particularly eager to make another adaptation of the `camera_single.py` script ([1](https://github.com/calizarr/PhenoPiSight/blob/master/pi_files/camera_single.py),  [2](https://github.com/maliagehan/gehan-bramble/blob/master/pi-files/camera_single.py)).

**Comment by nfahlgren** [comment]
@jshoyer makes sense. Reopen this issue or make a new one?
