### ISSUE TITLE
Cluester images top view wrong number of col

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#140]
![11_obj_on_img](https://cloud.githubusercontent.com/assets/24882807/24837646/c2551aba-1d30-11e7-9d41-ae1a6e2fc5be.png)
![12_clusters](https://cloud.githubusercontent.com/assets/24882807/24837647/c2573b7e-1d30-11e7-9741-f2179d60dd56.png)

Hello guys, i am doing a cluster to my lettuce top view image. I  specified 2 lines and 3 rows. As
`    device, clusters_i, contours = pcv.cluster_contours(device, img1, roi_objects, 2, 3, debug)`.
 But it is merging the 2ndand3rd columns dont know why..

Dont worry with the fact that the "red" lettuce are not being well perceived i ll probably change them to the green ones so that they are well perceived.

**Comment by MjBordalo** [comment]
I believe that the problem is that the bottom midle lettuce is "splited" in two. So probably when i change to all green lettuce the problem will be solved.

I have another question. I would like to get data as the VIS tutorial to the separated lettuces from this pipeline. How can i do it? i am not sure what kind of var `clusters_i` and `contours` are..

**Comment by maliagehan** [comment]
The rows and columns are based on the image size, and not the actual number of objects (think about how big you want the approximate ROIs to be). From your sample image, it looks like a better setting might be 3 rows, and 6 columns.

**Comment by maliagehan** [comment]
We do multi plant processing in two steps, first there is a pipeline to split the images, then another pipeline to run on the individual plants. This will change in version 3 but right now the parallelization script is expecting one output per image rather than multiple. So first you'd follow a tutorial like http://plantcv.readthedocs.io/en/latest/multi-plant_tutorial/ , then the normal vis tutorial on the split images. Hope that helps.

**Comment by MjBordalo** [comment]
@maliagehan Not sure if I got the ideia about the ROI. It isn't like doing a grid on top of the ROI or something like that?

I tryied it with 3 rows and 6 columns but it did no help much.
![12_clusters](https://cloud.githubusercontent.com/assets/24882807/24839506/981a756a-1d53-11e7-842d-398067f89d79.png)

**Comment by MjBordalo** [comment]
@maliagehan are you saying that i actually have to save the separated images and only after run an individual pipeline for the analysis of this saved files? 
It does not sound very efficient..
cant i get the images from cluster_contours function and call the analysis function over them ?

By the way when is the plantcv v3 planed to be available?
Thanks

**Comment by maliagehan** [comment]
It's definitely not the most efficient. You can use a loop like you are suggesting to run the analysis functions and to print out results files (multiple results files per image) within a single pipeline, then write a function to process the results files...but if you want to use plantcv_pipeline to parallelize the process and create a database then you currently need to run it over split images, because plantcv_pipeline is expecting to associate one image with one results file and not multiple. I analyze a lot of these types of images so I realize it's a problem, and will likely make an update sooner rather than later but it might take a few weeks since we're working on pushing 2.0 out.

PlantCV v 3.0 will likely be officially available next year, but as we make changes to plantcv they will be immediately available (we just package groups of changes into a released version about once a year). Hope that helps.
