### ISSUE TITLE
How do I Correctly Run a Sample Pipeline?

### ISSUE THREAD

**Issue by AntonSax** [danforthcenter/plantcv#151]
#### Details
I'm trying to use the tutorial located on this webpage: [http://plantcv.readthedocs.io/en/latest/vis_tutorial/](url)

I don't think I understand how to run the given sample command in jupyter notebooks. I can't seem to find the python files for the sample pipelines that would replace the code given here: 
`./pipelinename.py -i testimg.png -o ./output-images -r results.txt -w -D 'print'`

I'm using Windows 7.

**Comment by nfahlgren** [comment]
@AntonSax in the tutorial, the code blocks shown added together into a Python script file would be the hypothetical contents of the example `pipelinename.py`. We don't explicitly provide that as a script file, but that would be a good idea to include it so that you could see it in the tutorial and run it directly also.

The key difference between a pipeline and how you would run the same commands in Jupyter is mostly just that the pipeline scripts (as we make them) have the main and options functions, which are not necessary or desired in Jupyter. You can essentially ignore the options function altogether for Jupyter. The beginning of the notebooks need to be configured as described [here](http://plantcv.readthedocs.io/en/latest/jupyter/). To put the commands in the main function into Jupyter you would just need to modify them slightly, for example, this command:

```python
# Read image
img, path, filename = pcv.readimage(args.image)
```

would become something like the following in a Jupyter notebook cell:

```python
# Read image
img_file = "some_image_file.png"
img, path, filename = pcv.readimage(img_file)
```

Does that make sense? Happy to help further.

**Comment by AntonSax** [comment]
Yes, that helped me make sense of things. Thanks a lot!
