### ISSUE TITLE
Missing 16-bit images

### ISSUE THREAD

**Issue by AntonSax** [danforthcenter/plantcv#159]
### Description
In the [PSII pipeline tutorial](http://plantcv.readthedocs.io/en/latest/psII_tutorial/) one of the last steps is to [analyze FLU signal](http://plantcv.readthedocs.io/en/stable/fluor_fvfm/). The function requires 16-bit images, with no exception. I'm using the images provided on the github page in `docs\img\tutorial_images\psII` however they are in jpeg, which is only up to 8-bit. I can use other pictures for testing the function and the PSII pipeline, I'm just don't know if there is information I'm missing or if there are pictures I don't have.

The error I receive:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-94-d85a91fdbfe9> in <module>()
     11 fmax = cv2.imread(Fmax_img_file, -1)
     12 
---> 13 device, fvfm_header, fvfm_data = pcv.fluor_fvfm(fdark,fmin,fmax,kept_mask, device, outdir+'/'+filename, 1000, debug)
     14 
     15 # Output shape and color data

C:\Users\askz6\plantcv\plantcv\fluor_fvfm.pyc in fluor_fvfm(fdark, fmin, fmax, mask, device, filename, bins, debug)
     48     # Check that fdark, fmin, and fmax are 16-bit images
     49     if not all(i.dtype == "uint16" for i in [fdark, fmin, fmax]):
---> 50         fatal_error("The fdark, fmin, and fmax images must be 16-bit images.")
     51 
     52     # QC Fdark Image

C:\Users\askz6\plantcv\plantcv\fatal_error.pyc in fatal_error(error)
     12     """
     13 
---> 14     raise RuntimeError(error)

RuntimeError: The fdark, fmin, and fmax images must be 16-bit images.

```

**Comment by nfahlgren** [comment]
Hi @AntonSax, the images in the documentation, in many cases, may not work for testing because they were all converted to JPEG and reduced in size to make them small to avoid making the GitHub repo too large. This has come up before and I think what we should do is provide small test/sample data sets for download from a site at the Danforth Center, Figshare/Zenodo, etc. It might additionally be useful to specifically provide the original images that correspond to the images in the documentation, though that might be somewhat difficult both retroactively and also going forward (because we would have to add to some repository over time, which just might be hard to organize). What do you think, would sample datasets for various data types be a sufficient solution?

**Comment by AntonSax** [comment]
I think sample datasets would be a good idea, though I know there are already [public image datasets](http://plantcv.danforthcenter.org/pages/data.html) on the danforthcenter website. Ideally, the original images from the documentation would be the best, simply because results for those images are already available to compare to, and in my case I can check to see that any errors are due only to lost in quality and not an error on my part.

Thanks @nfahlgren .
