### ISSUE TITLE
Struggling with color correction tool

### ISSUE THREAD

**Issue by ryanskiba** [danforthcenter/plantcv#1606]
**Describe the bug**
transform.detect_color_card is either giving me an "IndexError" or a weird output depending on image orientation.

Originally, I was using transform.find_color_card to color-correct my images. This worked fine on one set of images, but on a recent set of images I would get the error message: fatal_error('No color card found under current parameters').

I figured that the function had finally deprecated to the point it was no longer usable, and switched to transform.detect_color_card. Although this isn't working for me either.

**To Reproduce**
input image: 
![IMG_9309](https://github.com/user-attachments/assets/a1e69b77-3b34-4c6c-9be1-15ad746625c6)

commands run:
import numpy as np
import argparse
import os
import sys
import cv2
from matplotlib import pyplot as plt
import pandas as pd
print("All modules loaded")

%matplotlib widget
from plantcv import plantcv as pcv
from plantcv.parallel import WorkflowInputs

args = WorkflowInputs(
    images=["imgs/IMG_9309.JPG"],
    names="image",
    result="example_results_oneimage_file.csv",
    outdir=".",
    writeimg=False,
    debug="plot"
    )

pcv.params.debug = args.debug

pcv.params.dpi = 100
pcv.params.text_size = 20
pcv.params.text_thickness = 20

img, path, filename = pcv.readimage(filename="imgs/IMG_9309.JPG")

card_mask = pcv.transform.detect_color_card(rgb_img=img)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[48], line 3
      1 #First, find the color card. You won't see any output of this function. 
----> 3 card_mask = pcv.transform.detect_color_card(rgb_img=img)

File [~\AppData\Roaming\Python\Python312\site-packages\plantcv\plantcv\transform\detect_color_card.py:105](http://localhost:8889/lab/tree/~/AppData/Roaming/Python/Python312/site-packages/plantcv/plantcv/transform/detect_color_card.py#line=104), in detect_color_card(rgb_img, label, **kwargs)
    103 corners = np.array(np.intp(cv2.boxPoints(rect)))
    104 # Determine which corner most likely contains the white chip
--> 105 white_index = np.argmin([np.mean(math.dist(rgb_img[corner[1], corner[0], :], (255, 255, 255))) for corner in corners])
    106 corners = corners[np.argsort([math.dist(corner, corners[white_index]) for corner in corners])[[0, 1, 3, 2]]]
    107 # Increment amount is arbitrary, cell distances rescaled during perspective transform

IndexError: index 7145 is out of bounds for axis 1 with size 6960

I then tried to do some trouble shooting. In the most recent color-correction tutorial, the color card has the white square in the top left. I figured that the tool may work better if that is the case, so I rotated my original image 180 degrees and ran the same commands as before. No error message this time, but this is the output:
![image](https://github.com/user-attachments/assets/a50274e1-29df-4b1c-ae96-df7a89e5f5da)

**Expected behavior**
I would expect a result similar to the tutorial.

**Local environment (please complete the following information):**
 - OS: Windows
 - Environment: JupyterLab launched from Anaconda Navigator
 - PlantCV Version: 4.3.1

**Additional context**
Additionally, I played around with the radius modifier, and tried cropping out the red tag and cropping out the words on the color card, but that didn't change anything.

**Comment by HaleySchuhl** [comment]
Hi @ryanskiba thanks for opening this issue. I'm struggling to download the input file. Would you be willing to zip it and share that way?

Also, in the meantime, have you tried adjusting the `min_size` parameter?

**Comment by ryanskiba** [comment]
[IMG_9309.zip](https://github.com/user-attachments/files/17400696/IMG_9309.zip)

Hi @HaleySchuhl, here is the compressed image. I just now tried increasing and decreasing the min_size parameter (not sure how it works) but I still got the same error message.

**Comment by HaleySchuhl** [comment]
Thanks again for bringing this to our attention, and for sharing your data @ryanskiba . I was able to replicate that error you ran into locally. I added a debug step to line 140 in the function, to see which objects are remaining after filtering takes place. It appears to me that the algorithm is removing too many color card chips under default parameters, and then tried to fit a grid diagonally to the subset of chips IDed successfully.

 
![Figure 4 (2)](https://github.com/user-attachments/assets/40776114-f6e1-440a-90de-e74174f29523)


I'm tried adjusting the optional keyword arguments and found that it's giving an intended result if I run 

```
card_mask = pcv.transform.detect_color_card(rgb_img=img, radius=105, adaptive_method=0, block_size=127)
```


![Figure 12 (1)](https://github.com/user-attachments/assets/9d945ea3-eab0-4699-aac0-1245226c4c2d)

![Figure 13](https://github.com/user-attachments/assets/8501da46-2dbf-4adf-b339-12f1d9dc31b4)


Hopefully that helps in the short term, please let us know if there are further questions. And I will open an issue so that we can catch that error and hopefully give a more informative error message in those situations like what came up in your image.

**Comment by ryanskiba** [comment]
Thanks for the quick response @HaleySchuhl! I appreciate your help.
