### ISSUE TITLE
error on running setup.py on a Mac install

### ISSUE THREAD

**Issue by akenyon** [danforthcenter/plantcv#165]
Title: error on running setup.py on a Mac install

### Description
On MacOS Sierra 10.12.5
with python 2.7.13
with OpenCV 2.4.13.2

I was following the installation instructions and everything worked until the "sudo python setup.py install", which gave the following error:

"error: SandboxViolation: mkdir(u'/Users/myname/.matplotlib', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available."

Let me know what I should do!

**Comment by nfahlgren** [comment]
Hi @akenyon, there are a couple things I can think of trying. Since the error suggests that setuptools is using `easy_install`, could you try running `sudo pip install .` in place of the `sudo python setup.py` command.

If that doesn't work, you might try to explicitly install matplotlib with pip and then run setup.

Let me know if neither of those options work.

**Comment by akenyon** [comment]
Hi @nfahlgren, it worked, thank you!

**Comment by nfahlgren** [comment]
@akenyon great! I need to do some more testing on OSX and will update the install instructions, but glad the workaround worked.
