### ISSUE TITLE
image_analysis scripts cause opencv crash on Lemnatec_Indoor fahlgren 2015 dataset

### ISSUE THREAD

**Issue by yanliu-chn** [danforthcenter/plantcv#18]
In plantcv source code, I tested the image_analysis scripts to handle three types of input images from the LemnatecIndoor image collection from http://figshare.com/articles/DDPSC_Phenotyping_Manuscript_1_Files/1272859 : NIR_SV, VIS_SV, VIS_TV. However, when i randomly pick three images from the sample data in box, one from each type, only VIS_SV worked with tweaking. The other two types crashed opencv.

Data is retrieved from https://uofi.app.box.com/terraref-box-shared/1/4678953842

The error I encountered is:
`
 OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)) in cvtColor, file /home/ubuntu/software/opencv/modules/imgproc/src/color.cpp, line 3959 Traceback (most recent call last): File "/home/ubuntu/plantcv/scripts/image_analysis/vis_tv/vis_tv_z3000_L1.py", line 118, in <module> main() File "/home/ubuntu/plantcv/scripts/image_analysis/vis_tv/vis_tv_z3000_L1.py", line 61, in main device, brass_mask1 = pcv.rgb2gray_hsv(brass_mask, 'v', device, args.debug) File "/home/ubuntu/plantcv/lib/plantcv/rgb2gray_hsv.py", line 14, in rgb2gray_hsv hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) cv2.error: /home/ubuntu/software/opencv/modules/imgproc/src/color.cpp:3959: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function cvtColor 
`
The command I ran is:
`
~/plantcv/scripts/image_analysis/vis_tv/vis_tv_z3000_L1.py -i ./VIS_TV_z3000_329934.jpg -o output 
`

**Comment by maliagehan** [comment]
I'm guessing that this script failed because it needs a mask image for the brass pieces on the track. Sorry, it should be required for the lemnatec images, but we've used in in the past on non-lemnatec images that didn't need the brass masking steps and turned the requirement off. You'll want the -m option and the mask images can be found /plantcv/masks/vis_tv/

If you send an error for the NIR images I can try to help you diagnose the issue. Cheers!

**Comment by yanliu-chn** [comment]
Great! The mask option worked for VIS_TV images. The images I tested is at https://uofi.app.box.com/terraref-box-shared/1/4678953842 . I basically randomly picked images to test.

Thanks a lot for the help!

**Comment by dlebauer** [comment]
@yanliu-chn can you post the code that worked for you? I think it was something like

```sh
/home/ubuntu/plantcv/scripts/image_analysis/vis_sv/vis_sv_z2500_L1.py \
  -i /home/ubuntu/plantcv-output/564214dce4b086fa6db9104f/VIS_SV_270_z2500_347208.jpg \
  -o /tmp/ \
  -m /home/ubuntu/plantcv/masks/vis_tv/mask_brass_tv_z2500_L1.png
```

But I am getting an OpenCV error

> OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)) in cvtColor, file /home/ubuntu/software/opencv/modules/imgproc/src/color.cpp, line 3959
Traceback (most recent call last):
  File "/home/ubuntu/plantcv/scripts/image_analysis/vis_sv/vis_sv_z2500_L1.py", line 107, in <module>
    main()
  File "/home/ubuntu/plantcv/scripts/image_analysis/vis_sv/vis_sv_z2500_L1.py", line 32, in main
    device, s = pcv.rgb2gray_hsv(img, 's', device, args.debug)
  File "/home/ubuntu/plantcv/lib/plantcv/rgb2gray_hsv.py", line 14, in rgb2gray_hsv
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.error: /home/ubuntu/software/opencv/modules/imgproc/src/color.cpp:3959: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function cvtColor

The jupyter notebook is here: so that I can reproduce it here: http://141.142.168.55/user/terra/notebooks/PlantCV%20demo.ipynb#

**Comment by yanliu-chn** [comment]
vis_sv images should use vis_sv masks. I think you used vis_tv masks. and vis_sv images don't need masks. only vis_tv and nir images need masks.

**Comment by dlebauer** [comment]
@yanliu-chn I get the same error without the `-m`

```
/home/ubuntu/plantcv/scripts/image_analysis/vis_sv/vis_sv_z2500_L1.py \
  -i /home/ubuntu/plantcv-output/564214dce4b086fa6db9104f/VIS_SV_270_z2500_347208.jpg \
  -o /tmp/ 
```

**Comment by yanliu-chn** [comment]
i need take a closer look. user 'ubuntu' can do it successfully, but user 'terra' or 'yan' failed with the error.
