### ISSUE TITLE
Add normalization / correction step to PlantCV pipelines

### ISSUE THREAD

**Issue by dlebauer** [danforthcenter/plantcv#19]
(Per discussion on Tuesday Dec 1 with @nfahlgren)

Add normalization and correction steps to the PlantCV pipeline so that the Clowder PlantCV extractor ([`extract.sh`](https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/extractors-plantcv/browse/bin/extract.sh)) produces phenotypes that could be used in a GWAS analysis.

This is the first step required for terraref/computing-pipeline#31

**Comment by nfahlgren** [comment]
To expand on this a little more, this is what I'm thinking. At the Danforth Center we use a script to parallelize PlantCV image analysis workflows (since image analysis can be broken down to a one image per CPU problem). That script is here: https://github.com/danforthcenter/plantcv/blob/dev/plantcv-pipeline.py

For the NCSA setup, parallelization will be managed by Clowder and the background PlantCV extractor. For the Clowder setup, we need to transfer some of the functionality of the plantcv-pipeline.py script to the workflow scripts that will be included in the Clowder extractor. I need to talk to Rob Alba to see what imaging configurations he plans to use for the sorghum experiments on the Danforth Center system so that I know which workflows we need to build for Clowder.

**Comment by dlebauer** [comment]
from @nfahlgren 

> Our older PlantCV scripts deal with one image at a time. It’s not strictly required, but the current scripts we use co-process an RGB and NIR (grayscale) image together. The way we do it on a file system is by filename, so if we are processing for example /path/to/VIS_SV_0_z500_h1_e82_g0_9000.png then once we create a mask for this image we apply it (after scaling) to the NIR image with roughly the same name: /path/to/NIR_SV_0_z500_h1_e82_g0_9005.png. The reason we started doing it this way is because the NIR images are lower quality than the RGB and are more difficult to process, but also turns out it’s faster to process this way too.

> Rob, you mentioned that the extractor could operate on Datasets rather than files. If we did it that way I could potentially write one analysis script for the all the files in a dataset. For the most part this is easy because there is nothing fundamentally different about different side-view rotation angles, including top-view would be the only unusual thing for us. This would add fewer jobs to the queue, but each job would be longer running.

**Comment by nfahlgren** [comment]
After discussion with Rob and Max, I will develop new PlantCV image processing scripts that simultaneously process VIS and NIR images and output normalized results in JSON/JSON-LD. Max will develop a new Clowder extractor that watches uploaded Datasets and triggers only when both the correct VIS and NIR images is uploaded.

**Comment by nfahlgren** [comment]
Merged into TERRA-REF computing-pipeline: https://github.com/terraref/computing-pipeline/pull/108
