### ISSUE TITLE
Beginner's confusing tutorials -VIS Image Pipeline

### ISSUE THREAD

**Issue by Geo-Trackers** [danforthcenter/plantcv#198]
I am a beginner to Plant CV and Computer vision related stuffs. I have been trying to followup the tutorials for plant CV and have been using Jupyter as mentioned in documentation of Plant CV. I tried copy pasting The Walk Through A Sample Pipeline on VIS Image Pipeline, but it neither output any image nor shows any errors. It seems to work but i am not getting any outputs. 

It would be great to have more detailed tutorials. 
The procedure i followed was copy paste the code in Jupyter working with Python 2 and i save the file in .pynb. Then i go to the terminal on my Ubuntu 16.04 64 bit LTS, and there i first change the .pynb to .py

After that i followed **./pipelinename.py -i testimg.png -o ./output-images -r results.txt -w -D 'print'**
which in my case looks like " sudo python hello.py -i sample.jpg -o ./output-images -r results.txt -w -D 'print' "

This doesnt show up any errors but doesnt load the image. I hope i posted on the right page and look forward to hear the mistake which i have been making. 

Thank you 

Best Regards, 
Suman

**Comment by nfahlgren** [comment]
@Geo-Trackers the issue might be that the code in the VIS tutorial is written as it would appear in a PlantCV pipeline Python script. It has an argument parsing function (`options`) and a `main` function. These will not work properly in a Jupyter notebook since it's not executing code on the command-line. The VIS tutorial code would need to be updated somewhat to work in Jupyter (essentially updated in the reverse of what is described in the [Jupyter documentation](http://plantcv.readthedocs.io/en/latest/jupyter/#converting-jupyter-notebooks-to-plantcv-workflow-scripts)).

For converting from Jupyter to a Python script, the `.ipynb` file (JSON format) has to be converted to Python code. That can be done either directly in a Jupyter notebook by clicking File -> Download as -> Python (.py) or by running the command `jupyter nbconvert --to python notebook.ipynb` on a notebook file. Once it's converted it usually needs to be modified somewhat to run correctly as a command-line application (as described in the link above for PlantCV).

I can give you a more concrete example of this process for some pipelines I have developed. In this repository https://github.com/danforthcenter/plantcv-terra you will see a `notebooks` and `scripts` folders. For every notebook in the notebooks folder there is a matching script in the scripts folder. I developed the notebooks first, exported them as Python scripts and modified them to run as PlantCV pipelines. 

Hopefully that helps a little, let me know if not though.

**Comment by Geo-Trackers** [comment]
@nfahlgren  This would really help. I intend to apply PlantCV for counting number of banana plantation in an aerial image taken above 50-60 m above the ground. I didnt find much documentation for aerial imagery crop counting in the internet but i think this can do. Do you have experience in working with aerial imagery in PlantCV?
 Thank you so much for your prompt response. I look forward to hear from you.
Best 
Suman 
Nepal

**Comment by Geo-Trackers** [comment]
@nfahlgren Could you also elaborate on how VIS tutorial code needs to be updated in reverse? I went through your scripts which and modified mine accordingly, but still i am confused on the argumentation that needs to be supplied on the python code.

It would be great if you could give me a walk through for lets say converting RGB to LAB and extracting L using PlantCV or any other basic examples. 


Thank you so much 

Best 

Suman

**Comment by nfahlgren** [comment]
@Geo-Trackers if you start with a Jupyter notebook then to convert the notebook into a script there's our argument parsing function (or something like it) that needs to be added to the notebook code. But if you are starting with a script and want to go to a notebook then the argument parsing needs to be replaced with an alternate approach to defining inputs (usually just hard coded since the notebook is a development environment). So for example, if you have a short script that looks like the following (just reads in an image):

```python
#!/usr/bin/env python

import cv2
import plantcv as pcv
import numpy as np
import argparse


# Parse command-line arguments
def options():
    parser = argparse.ArgumentParser(description="Process side-view images from the TERRA-REF LT2 experiment.")
    parser.add_argument("-i", "--image", help="Input VIS image file.", required=True)
    parser.add_argument("-r", "--result", help="VIS result file.", required=True)
    parser.add_argument("-r2", "--coresult", help="NIR result file for the co-processed image.", required=True)
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
    parser.add_argument("-w", "--writeimg", help="Create output images.", default=False, action="store_true")
    parser.add_argument("-d", "--debug", help="Turn on debug, prints intermediate images.", default=None)
    args = parser.parse_args()

    # If debug is not None then set debug mode to print
    if args.debug is not None:
        args.debug = "print"

    return args

# The main workflow
def main():
    # Initialize device
    device = 0

    # Parse command-line options
    args = options()

    # Read image
    img, path, filename = pcv.readimage(filename=args.image, debug=args.debug)

if __name__ == '__main__':
    main()
```

To run the same code in a notebook you would need to replace the `args` and function components. There are different ways this can be done. In my examples it would look like:

```python
%matplotlib inline  # Added this line
import cv2
import plantcv as pcv
import numpy as np
import argparse

# Instead of the args inputs I define a variable manually for each input I need
image = "./LT2/snapshot138498/VIS_SV_0_z1_h1_g0_e65_v500_276569_0.png"
debug = "plot"
writeimg = False
result_file = "test_results.txt"
coresult_file = "test_coresults.txt"

# The code below here is from the "main" function in the script
device = 0

# Read image (note that args.image and args.debut are replaced with image and debug)
img, path, filename = pcv.readimage(filename=image, debug=debug)
```

However, to make the transition between notebooks and scripts even easier, I was thinking recently about building a structure that mimics the args object so that one would not have to rename variables. The script side would still need to contain the same `options` function to do proper command-line argument parsing, but in Jupyter you could do this:

```python
%matplotlib inline  # Added this line
import cv2
import plantcv as pcv
import numpy as np
import argparse

# Instead of the args inputs you could define an args class with the manual inputs
class options:
    def __init__(self):
        self.image = "./LT2/snapshot138498/VIS_SV_0_z1_h1_g0_e65_v500_276569_0.png"
        self.debug = "plot"
        self.writeimg = False
        self.result = "test_results.txt"
        self.coresult = "test_coresults.txt"

# Parse options
args = options()

# The code below here is from the "main" function in the script
device = 0

# Read image (note that args.image and args.debut are replaced with image and debug)
img, path, filename = pcv.readimage(filename=args.image, debug=args.debug)
```

**Comment by Geo-Trackers** [comment]
@nfahlgren  Thanks so much for your quick walk through. It works now. BTW, have you applied PlantCV for applications such as crop counting in aerial imagery? I didn't find much documentations online regarding this.  I have attached the aerial image collected at 100 m above the ground, similar to the one i intend to apply image recognition for crop counting & ultimately predicting yield.

![sample_image](https://user-images.githubusercontent.com/7304644/32430103-4d0d68f4-c300-11e7-8eb3-70faf28d001d.jpg)

Cheers
Suman

**Comment by nfahlgren** [comment]
@Geo-Trackers sorry for the delay. We do not have any examples of that type of problem yet. My hunch is that this might require a machine learning-type approach. You are interested in identifying individual trees or plots?

**Comment by Geo-Trackers** [comment]
@nfahlgren I have been trying to detect individual trees, however i think this is a tough job therefore i am planning to detect plot wise detection of the trees. Being a beginner i am having difficulties in achieving my objective, so if you find something across the internet, please let me know.

**Comment by jamesthesken** [comment]
@Geo-Trackers I'm working on a very similar problem right now and am trying to determine the approach. ML classifiers are quite confusing for this, given the difficulty in creating datasets that hold images of rows of trees. Have you figured anything out? Look forward to hearing back.

I also just wrote a post about row detection using OpenCV: https://medium.com/@jamesthesken/crop-row-detection-using-python-and-opencv-93e456ddd974

**Comment by nfahlgren** [comment]
Closing for now but feel free to reopen if needed!
