### ISSUE TITLE
Metadata for figshare dataset 1

### ISSUE THREAD

**Issue by jshoyer** [danforthcenter/plantcv#22]
A few suggestions for a version 13 of https://figshare.com/articles/DDPSC_Phenotyping_Manuscript_1_Files/1272859
- [ ] Add DOI for the relevent publication:
  http://doi.org/10.1016/j.molp.2015.06.005
- [ ] Add link to plantCV v1 source code archive:
  http://doi.org/10.6084/m9.figshare.1447311
   - Details about which script produced which output file would be nice.
     Even better would be a Makefile to regenerate the ouput on demand.
   - Aside: the [figshare page]
(https://figshare.com/articles/PlantCV_release_v1_0_Plant_image_analysis_using_Open_Computer_Vision_OpenCV_/1447311)
     for the archived source tree
     is really terrible:
     no DOI and no link to GitHub commit on that page.
     Could archiving on Zenodo be any better?
- [ ] Add a ReadMe file
  - I will try to find time to draft one.

**Comment by nfahlgren** [comment]
I will talk to @maliagehan about adding the DOIs as she owns the repository. One feature missing from Figshare (I think?) is that it does not really allow you to collaborate on a repository.

The Makefile is a good idea, but it is probably something we would do next time. I would have to sit down and learn how to make one and it is not something we actually used for the paper.

That is weird about the Figshare release page. It definitely has a DOI (10.6084/m9.figshare.1447311). I have also been thinking Zenodo might be a better option but I do not remember why I thought that off hand. I find Figshare very awkward to work with, so that is probably part of it.

**Comment by jshoyer** [comment]
I am closing this issue because I think it might be simpler to just leave the figshare data set the way it is. Feel free to reopen. I too feel that figshare is awkward and that better sharing solutions will appear---maybe clowder or whatever.

It is probably more useful to send people to the following link instead instead of figshare: http://plantcv.danforthcenter.org/pages/data-sets/2013/setaria_burnin2.html

I see now that one is supposed to click the "Cite" button on the figshare page to see its DOI.

I revisited this because I was trying to understand plantCV databases. I found the discussion here useful (because I was particularly interested in metadata): https://github.com/terraref/computing-pipeline/issues/36
