### ISSUE TITLE
Just downloaded, but having troubles getting it to work

### ISSUE THREAD

**Issue by cwehrman6** [danforthcenter/plantcv#233]
### Description

I'm fairly new to python and coding in general so my lack of experience may be the problem here.
On Windows 10 using anaconda.
I'm attempting to run the example VIS pipeline that is posted, but I keep running into this error.

(plantcv) C:\Winfield\plantcv>python plantcvtest.py -i original_image.jpg -o output\test_data -r results.txt -w -D 'print'
define_roi function will be depricated in the near future, please use the roi subpackage, which has the same functionality
WARNING: Make sure ROI is COMPLETELY in frame or object detection will not perform properly
Warning: Invalid contour.
Traceback (most recent call last):
  File "plantcvtest.py", line 125, in <module>
    main()
  File "plantcvtest.py", line 98, in main
    device, shape_header, shape_data, shape_img = pcv.analyze_object(img, args.image, obj, mask, device, debug, args.outdir + '/' + filename)
  File "C:\Winfield\plantcv\plantcv\plantcv\analyze_object.py", line 40, in analyze_object
    if len(obj) < 5:
TypeError: object of type 'NoneType' has no len()

I have no idea what I'm doing wrong since I'm using the same image the example used and I haven't changed their code at all. (except action="store_true" was missing from the -w argument definition)

Seems to be similar to issue #66, but they didn't have a definitive solution.

Any help would be greatly appreciated.

**Comment by maliagehan** [comment]
hi Curtis, just wanted to confirm that you didn't use the images shown on the documentation as your actual input image (you didn't right click save for example). For viewing purposes these images have been downsized so we don't make the documentation too large. If you did right-click save the images and use them as an input that could be the source of the error since the settings were made for a larger image.

**Comment by cwehrman6** [comment]
I did right click save the image, but i tried with input_color_img.img which was downloaded with plantcv/tests/data and that resulted in  the same error message

**Comment by maliagehan** [comment]
Got it, in both of those cases that pipeline was probably not set up for the images are you inputing so there would need to be setting changes to the pipelines in order to work with the images you inputted. 

1. The ROI warning about deprecation is simply a warning, however if the input image you are using is a different size than the image that the pipeline was set up for you may have a ROI that is going out of frame, this causes big errors downstream. The errors you are getting are usually triggered when no object is detected (this usually happens if settings are incorrect for the input images). 
2. You can run a pipeline with the Debug on so that you can see where there is something going wrong. It is always easier to set up pipelines using the new jupyter integration, there is documentation for that here: https://plantcv.readthedocs.io/en/latest/jupyter/
3. There are sample jupyter notebooks for plantcv in a number of places: https://github.com/danforthcenter/reu and also here: https://github.com/danforthcenter/plantcv-workshop

**Comment by cwehrman6** [comment]
I had initially tried to avoid using jupyter notebooks because I didn't understand how they work. Since you recommended them I went and learned how they work. Using that, I did manage to get it working and convert to a python file with the sample image.

Thank you so much for the help and the sample jupyter notebooks!
