### ISSUE TITLE
Dual VIS/NIR and PSII Imaging

### ISSUE THREAD

**Issue by cwehrman6** [danforthcenter/plantcv#238]
I have been looking dual VIS/NIR dual processing using a setting very similar to the octagon using raspberry pis. Is that even possible? I wasn't sure if the VIS and NIR images need to be taken from the exact same spot or just relatively close. If it can be done, would more pis be needed than? Any thoughts or advice would be helpful.

I'm also wondering how PSII imaging is done. What kind of camera do you use? Is a special setup needed? Can raspberry pis do this also?

**Comment by nfahlgren** [comment]
@cwehrman6 in the VIS/NIR pipeline we scale the size of the VIS mask to fit on the NIR image with the assumption that the cameras have the same perspective of the plant. If the cameras have a different perspective then a different kind of transformation would be more appropriate. There are tools to do this kind of thing but we have not included tools for that in PlantCV yet. OpenCV, scikit-image, and other tools can definitely be used with PlantCV though (e.g. homography transformation https://docs.opencv.org/3.4.1/d9/dab/tutorial_homography.html).

The PSII imaging system is a CCD camera with a cut filter on it to filter out light other than the chlorophyll fluorescence signal it's designed to detect. The camera system also has an LED panel that produces a red-light pulse at 3000 umol/m^2/s to induce chlorophyll fluorescence. There's a lot of tricky timing of the pulse and imaging that would be difficult to build. It's also pretty dangerous because of the high intensity light pulse, so safety features would need to be included to prevent eye damage. The system we have is produced by a company called PhenoVation (http://www.phenovation.com/). The Kramer lab at Michigan State also builds similar kinds of systems (https://prl.natsci.msu.edu/people/faculty/david-m-kramer/).

**Comment by maliagehan** [comment]
I'll add that if the images can be rescaled and the images are not so different in perspective, then you can shift them using the shift image function so they will overlay with the resize function (so relatively close would work).

**Comment by maliagehan** [comment]
Feel free to reopen this issue if you have more questions on VIS/NIR pipelines, but will close this issue for now.
