### ISSUE TITLE
changes to commands for trial with one picture prior to setting up a pipeline

### ISSUE THREAD

**Issue by huberma** [danforthcenter/plantcv#242]
changes to commands for trial with one picture prior to setting up a pipeline

### Description
As suggested in the tutorial of PlantCV, you should make a trial on one example picture before transforming it into a pipeline and then actually run it for all the pictures to be analyzed. I'm working with the Jupyter notebook and I realized that I have to make some small adjustments in the commands given in the tutorial for the "VIS image pipeline".
There it is actually not necessary to import sys and os, as far as I understood.

Then, at the point where the tutorial for Jupyuter ends, then the VIS tutorial starts with the pipeline (which has to be written in the terminal), where I would actually like to continue with the analysis for one picture. Which adaptions do I have to make for this?

**Comment by nfahlgren** [comment]
Hi @huberma could you provide more detail? I am not sure what the question is.

**Comment by huberma** [comment]
Hi Noah,

Sorry, as I'm a total beginner in this field, it is still hard for me to describe a bioinformatical issue. 
Here the questions:

1. In the installation manual it is recommended to work with the environment, 
but then it is not clear in the tutorial for “Jupyter” - because “if it's not installed in the global python path” then you should import sys.” But is this actually necessary?
3. I want to optimize the analysis for one picture before transforming it into a pipeline. For this, I followed the tutorial for Jupyter. From where it ends, I continued with the commands from the VIS tutorial, but this is written for a pipeline (which has to be written in the terminal). 
So if I want to do the trial with one picture, before setting up the pipeline, which changes do I have to make for the first commands in the “VIS pipeline” tutorial?

I hope this is more clear now.

**Comment by nfahlgren** [comment]
Hi @huberma,

No worries, all questions are welcome here! 

The short answer is that there is more than one way to work with PlantCV, so the documentation is written to support these multiple routes. What's most important is to get comfortable with the general principles so that you can piece together the right aspects for your analysis problem(s). But I totally understand that when one is first getting started, having multiple options can actually make things harder.

For Jupyter, you are correct that you do not need to import sys or alter sys.path if you have installed PlantCV to a place where Python can "see" it (e.g. if you used the Anaconda installation method). In other words, in Jupyter if `from plantcv import plantcv as pcv` works without modifying sys.path then you are good to go. 

The Jupyter tutorial itself is only about getting Jupyter set up to use PlantCV as you have found. Your instinct to then use the VIS tutorial to start building an analysis workflow for your images is correct also (as long as you are working with RGB images). But you are also correct that the complete code in the VIS tutorial was written as a pipeline script, not as a notebook, so it cannot be copied and pasted directly into Jupyter per se. Here's what I generally do to build a notebook that can be converted to a script later with minimal reformatting. Our VIS tutorial starts with this:

```python
#!/usr/bin/python
import sys, traceback
import cv2
import numpy as np
import argparse
import string
from plantcv import plantcv as pcv

### Parse command-line arguments
def options():
    parser = argparse.ArgumentParser(description="Imaging processing with opencv")
    parser.add_argument("-i", "--image", help="Input image file.", required=True)
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
    parser.add_argument("-r","--result", help="result file.", required= False )
    parser.add_argument("-w","--writeimg", help="write out images.", default=False)
    parser.add_argument("-D", "--debug", help="Turn on debug, prints intermediate images.", default=None)
    args = parser.parse_args()
    return args
```

This won't work in Jupyter, but we can mimic this functionality like so (pared down a bit):

```python
import cv2
import numpy as np
from plantcv import plantcv as pcv

### Define a class for input options
class options:
    def __init__(self):
        self.image = "your-test-image.png"
        self.debug = "plot"
        self.writeimg = False
        self.outdir = "."
        self.result = "test_results.txt"
```

Then the VIS tutorial continues with:

```python
### Main pipeline
def main():
    # Get options
    args = options()

    # Read image
    img, path, filename = pcv.readimage(args.image)

    # Pipeline step
    device = 0
```

Which we can change to:

```python
# Get options
args = options()

# Read image
img, path, filename = pcv.readimage(args.image, args.debug)

# Pipeline step
device = 0
```

And then continue on adding each PlantCV command into a new cell.

Hopefully that helps a bit. If you want to see some more examples in Jupyter specifically, we have some example notebooks in this GitHub repository: https://github.com/danforthcenter/plantcv-workshop. Some of them are a little out of date though, so they may need to be altered a bit to get working.

**Comment by huberma** [comment]
Hi @nfahlgren !

Thank you very much for your detailed explanation!
And thank you for understanding my doubts and questions and giving the right answers to them :)
I tried and I get a problem with this command
`img,` path, filename = pcv.readimage(args.image, args.debug)

![image](https://user-images.githubusercontent.com/41013055/42688016-fc9bf944-869a-11e8-9d28-9179227951cc.png)








Do I need to add another command before that?

**Comment by nfahlgren** [comment]
Hi @huberma!

It looks like it can’t find the image file `your-test-image.png`. In the `options` section of the code the name of the file, including a path to it, can be adjusted. For example, on my computer I might have an image in my download folder that I could enter like:

```python
class options:
    def __init__(self):
        self.image = "/Users/nfahlgren/Downloads/2018-07-07_00-00-00-camera1.png"
        self.debug = "plot"
        self.writeimg = False
        self.outdir = "."
        self.result = "test_results.txt"
```

In Jupyter when your mouse cursor is inside the quote characters you can use the tab key to bring up a menu to autocomplete filenames and paths so that you don’t have to type out the whole thing (not always helpful, but it can be most of the time).

**Comment by huberma** [comment]
@nfahlgren 

I changed the command with the name of one specific image and now it works :)
![image](https://user-images.githubusercontent.com/41013055/42694907-24d1cae2-86b4-11e8-8c91-29c1ca64b481.png)

**Comment by nfahlgren** [comment]
Great!

**Comment by huberma** [comment]
Thank you very much for your help @nfahlgren !
I will also check out some other example notebooks to get an idea how I can adapt the script to my images.
