### ISSUE TITLE
AttributeError  

### ISSUE THREAD

**Issue by asumann** [danforthcenter/plantcv#246]
I've switched to use Anaconda with Py2.7. However, I keep having this error:

> AttributeError: 'module' object has no attribute 'readimage'`

Whatever I tried didn't solve this. What do you suggest?

Thanks,

**Comment by nfahlgren** [comment]
Hi @asumann, it sounds like one of two things I can think of.

1. If you did only `import plantcv` there is no `readimage` function at that level of the package because we made `plantcv` a namespace package, so instead you now need to do `from plantcv import plantcv as pcv` (the as pcv is optional).
2. You might get something weird like that if you are working on the command-line and your current position is in the plantcv folder because it will try to import it locally before it imports the installed version.

Either of those things relevant or something else going on?

**Comment by asumann** [comment]
Thanks again @nfahlgren!! First one definitely worked well.

**Comment by maliagehan** [comment]
Sounds like this issue is resolved, but feel free to reopen if you have a related issue.
