### ISSUE TITLE
Color Correction - how does it work?

### ISSUE THREAD

**Issue by JLJ90** [danforthcenter/plantcv#254]
### Question regarding how to use color correction.
 

Hello, I am interested in analysing the color of images. From the web call that was in early Septmeber, I remember Malia talking about the new color correction function.  I am very intrigued as to how it works.

Looking at the code, it references 22x4 color chips. Is this something like x-rites color passport? 

Is it the case where you have an image of the color card alone as the standard, and then you would compare all other images to this and adjust as necessary?

**Comment by nfahlgren** [comment]
Hi @JLJ90, you are correct, in our examples we used the X-Rite Passport. The user defines where each color chip is though, so in principle any color reference card can be used, so long as a good transformation model can be built. We found that in our case fewer than 8 chips was not enough data to build a model. The documentation provides some Jupyter code that can be used to generate the labeled grayscale image that tells PlantCV where the each chip is.

Once the color chips have been labeled, there are two strategies available for doing color correction. The most robust model is to have a color card in every image. One image is chosen as the target (or reference) image and the color card data is extracted. For all other source images, the color card is also extracted and the color card data for each target-source image pair are used to create a transformation matrix to adjust the source image. This method works when you have relatively frequent imaging condition variability.

In the second strategy, you might only have images of color cards taken periodically (e.g. once per experiment). You still do the same process, choose one as the target and the rest as source images. A transformation matrix is created for each target-source pair. Then images without color cards are corrected by applying the relevant transformation matrix. This method works when you're imaging conditions are relatively stable within one experiment (or block) and you want to make bulk adjustments to increase uniformity between experiments. Or other bulk adjustments to color profiles.

**Comment by nfahlgren** [comment]
Hi @JLJ90, it looks like your chip labels do not line up correctly with the chips. I created a Jupyter notebook with a helper function I put together to make labeling chips easier: https://github.com/nfahlgren/shared_jupyter_notebooks/blob/master/JLJ90_color_correction.ipynb. However, this did not solve the problem (completely anyway). I am not totally sure what is going on with the artifacts in the corrected image. I suspect that maybe one of the color channels in these two images is saturated and it fails to build a good model for the transformation but I would need to look into the data more carefully. @jberry47 any ideas?

**Comment by jberry47** [comment]
Hi @JLJ90, I inspected your target image and just as @nfahlgren suspected the problem is due to over saturation. In the red channel of your target image, there are 7 chips that are totally saturated (all pixels are 255). The blue and green channels are all okay. An easy way to check for over saturation is to import your image into ImageJ, use Analyze -> Histogram, press the "live" button, and move an ROI over all the chips and inspect each RGB histogram. If in any of the channels, any of the chips are all 255, then color correction with this algorithm will fail just as you're observing. Below is an example of what I did to inspect your target image and note how the min and max of the red chip are both 255. I suspect that since the red channel is over-exposed, simply dropping the chips that are saturated won't be a working solution but it may be worth a shot just to see what happens. 

![screenshot from 2018-11-17 15-14-12](https://user-images.githubusercontent.com/20114985/48665849-83eca080-ea7b-11e8-8bf6-d8acbd5d2410.png)

**Comment by JLJ90** [comment]
Thank you both for the help @nfahlgren @jberry47. Both responses were very useful, I shall have a go with dropping the fully saturated chips and report back my findings. I'm assuming this is something that can only be fixed with changing settings on my camera. Do you have any recommendations for camera settings that would alleviate this? Otherwise, I will just fiddle with the settings until I get something that is not fully saturated. 

Thanks again!

**Comment by jberry47** [comment]
Happy to help @JLJ90! The first setting I would locate on your camera is the "exposure compensation" and play with that first. This feature will under or over expose an image based on ISO step units. Otherwise you can switch your camera to full manual and individually adjust the gains of each RGB channel but this is not very fun or intuitive. 

Good luck!

**Comment by nfahlgren** [comment]
Hi @JLJ90, the issue is only with the "debug" image output. It's because we are using `np.hstack` to line up the uncorrected source, corrected source, and target image together for visualization purposes. Horizontally stacking the images requires them to be the same size though, so that broke an assumption of ours. To get around this you can set `pcv.params.debug = None` and then run `pcv.transform.correct_color`. To visualize the corrected image you can use `pcv.plot_image(corrected_img)` (or pcv.print_image if you are not in Jupyter). I'll have to think about how to get around the issue. We could either stop using `np.hstack` and just plot the corrected image, or we could pad the smaller images for plotting purposes.

**Comment by nfahlgren** [comment]
I forgot to mention, I added the function from the Jupyter notebook to PlantCV as a helper function for making the mask: https://plantcv.readthedocs.io/en/latest/transform_correct_color/#create-a-labeled-color-card-mask. If that's helpful at some point.

**Comment by JLJ90** [comment]
I was using the helper function it was very useful!


I thought I would share some results after the color correction procedure.

Target  - pixel samples of red chip 

196,60,62 | 194,61,64 | 195,62,67 | 195,61,68





![image](https://user-images.githubusercontent.com/35571955/49327450-dfc62780-f559-11e8-945f-3bd4dd6401d2.png)

Source  - pixel samples of red chip


200,58,70 | 194,54,65 | 197,60,70 | 198,67,73



![image](https://user-images.githubusercontent.com/35571955/49327460-008e7d00-f55a-11e8-84f5-a98976a54433.png)


Corrected  - pixel samples of red chip 

214,66,100 | 210,79,100 | 209,77,103 | 210,73,104 | 212,73,104





![image](https://user-images.githubusercontent.com/35571955/49327472-261b8680-f55a-11e8-98f5-b2d9c5668215.png)

The images were quite close to start with, w.r.t the red chip values, I was just running the code for testing purposes. From the output I have shown, would this be expected behaviour? 

I am not sure if I have the theory behind this correct, but I was assuming the values would be closer, not further to the target.

**Comment by jberry47** [comment]
Hi @JLJ90 I ran the correction as well and got a very similar image to what you've produced. This is the standardized source image. 
![source_corrected](https://user-images.githubusercontent.com/20114985/49329633-98cf3680-f547-11e8-99d6-4f239c007879.jpg)

One major problem with color correction is spotlight effect. This effect is more prominent in close up shots such as the ones you're taking. I've done a couple tests in ImageJ to detect this effect and I believe you have a small amount of it. What you need to do is draw a small rectangular ROI on the top edge of the card like this and run Analyze -> Plot profile. 
![image](https://user-images.githubusercontent.com/20114985/49329674-2f035c80-f548-11e8-92b5-c64a07826857.png)

The new window shows the x-position of the ROI on the xaxis and the average gray value on the yaxis. If the line is not flat, you have some amount of spotlight effect. When doing color correction, this spotlight effect has to be perfectly identical between source to target. I used plot profile on your source and target images and I found that there are differing slopes between them. 
![screenshot from 2018-12-01 08-59-23](https://user-images.githubusercontent.com/20114985/49329703-b650d000-f548-11e8-8db2-19befed567dd.png)

We know that spotlight effect is a problem and unfortunately we don't have a solution just yet. There are algorithms out there that correct for spotlight effect so in the future that will certainly be a priority to manage. In the meantime, you might want to consider ways to limit non-uniform lighting in your images. Two great ways that I've used is to invest in a good light diffuser and not being too close to objects in the scene when taking the picture. Right now you are very very close to having the same light conditions between your source and target so I imagine that a small change to your imaging methods would be enough to fix the problem.

**Comment by jberry47** [comment]
Hi @JLJ90 sorry for the delay in getting back to you. You are exactly correct about how non-uniform light effects the gray values of the RGB values of the color checker. If one side is more illuminated then the regression method used in the correction will be very biased and produce artificial colors like what we're observing. I did notice that you were able to adjust the overall brightness in the second source image you provided. I checked all your chips and they look great in every channel. 

Light diffusers are great for turning "hard" light into "soft" light. "Soft" light is simply scattered photons and scattering is increased quadratically with distance. So the further the light source and camera are from the objects, the softer and more uniform the lighting is across your scene. That's why I've found that if you can get the camera a little further away than expected, color correction performs as it should.

And thanks for the suggestion to get a document together addressing all these issues. It would be very helpful for many people if something was created to bypass these issues before they occur.

**Comment by HaleySchuhl** [comment]
Color card chip over/under saturation is something that has come up more than once, so we've added a function to help quickly check all the color card chips for any issues. There is an example of a "good" and "problematic" result in the [color correction tutorial](https://plantcv.readthedocs.io/en/latest/transform_color_correction_tutorial/#checking-the-color-card-chips). 

Please feel free to reopen this issue with other comments or questions regarding color correction!
