### ISSUE TITLE
img from analysis functions empty

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#277]
Really nice job with the VIS tutorial! 1.5 things that stuck out to me:
at the very end, for the analysis, the code posted doesn't actually run in a jupyter cell because 1. indentation 2. args does not exist.  

I removed those problems but then found that
analyze_object(), analyze_bound(), analyze_color() all return empty arrays for the images. Looks like you only output the image if `area` and `filename` are defined. any reason for this? 
I realized ` pcv.params.debug = 'plot' ` also shows the plots but it be nice to have this flexibility to see the plots separately. As presented one would expect the images be output, even if `filename` (in my case) are not defined. If `area` is not defined you might actually consider a warning message.

**Comment by nfahlgren** [comment]
Thanks @dschneiderch! The tutorial was written as a walkthrough of an analysis workflow Python script, which is why there's the indentation, but definitely agree it makes switching the code examples over to Jupyter more of a chore. Plus as you said Jupyter would not use argparse. One of our goals (#201) is to develop Jupyter-based interactive documentation using Binder, the idea being that each static page in Read the Docs would have an accompanying launchable Jupyter notebook with the code and example data. That being said, no reason we couldn't reformat the existing documentation.

The image arrays for the analyze functions will be empty as you observed when `filename` is undefined. Filename is used as a switch (in addition to the prefix) to turn on or off output images. The idea was that a user might not want to output the images to speed up analysis and/or reduce output storage size. I just noticed that our code is somewhat incorrect, this section:

```python
outfile=False
if args.writeimg==True:
    outfile=args.outdir+"/"+filename

# Find shape properties, output shape image (optional)
shape_header, shape_data, shape_img = pcv.analyze_object(img, obj, mask, args.outdir + '/' + filename)

# Shape properties relative to user boundary line (optional)
boundary_header, boundary_data, boundary_img1 = pcv.analyze_bound_horizontal(img, obj, mask, 1680, args.outdir + '/' + filename)

# Determine color properties: Histograms, Color Slices and Pseudocolored Images, output color analyzed images (optional)
color_header, color_data, color_img = pcv.analyze_color(img, kept_mask, 256, 'all', 'v', 'img', args.outdir + '/' + filename)
```

Would be better like:
```python
outfile=False
if args.writeimg==True:
    outfile = os.path.join(args.outdir, filename[:-4])

# Find shape properties, output shape image (optional)
shape_header, shape_data, shape_img = pcv.analyze_object(img, obj, mask, outfile)

# Shape properties relative to user boundary line (optional)
boundary_header, boundary_data, boundary_img1 = pcv.analyze_bound_horizontal(img, obj, mask, 1680, outfile)

# Determine color properties: Histograms, Color Slices and Pseudocolored Images, output color analyzed images (optional)
color_header, color_data, color_img = pcv.analyze_color(img, kept_mask, 256, 'all', 'v', 'img', outfile)
```

Then the output images obey the boolean user input `--writeimg`.

The output images variable (e.g. shape_img), if outputs are enabled, will hold the list of the locations of each output image, and these will be stored in the output database. 

A warning and other handling of errors when `area` is not defined would definitely be useful. I thought at the moment that there is normally a fatal error when area is not defined because the `pcv.object_composition` function will fail when there are no contours to combine. I have been recently adding in a check for no area or no contours ahead of the object composition and all analyze function steps to skip them when no plant is detected. But that's a long way of saying that a warning to make that clear would be useful!

**Comment by dschneiderch** [comment]
Thanks for the explanation. 

So at the moment is there a way to interactively run through this? Presumably I could define `outfile = "C:\Users\Dominik Schneider\Downloads"`  to give it a location to save those files to, but it's unclear to me what is expected of filename or where it is defined. is this the same `filename` that is output from `pcv.readimage`?

**Comment by nfahlgren** [comment]
It depends on your preference, but what will happen functionally is this. Let's say I put `filename=test.png`. `pcv.analyze_object` will output two images, `test_shapes.jpg` and `test_mask.jpg`, into the current working directory. If you run this analysis on multiple images this is probably not desirable because all the output images will have the same name. So as you said, I would generally use the `filename` variable that is output by the `pcv.readimage` function because you can then link the output image names to the input image name. The same goes for the output directory. You can either code this directly into your script or you can use an input variable to set the output directory. In your case you could set `outfile = "C:\Users\Dominik Schneider\Downloads\" + filename` to put all the output files in Downloads with the original image name plus the new suffix.

**Comment by dschneiderch** [comment]
I was a little confused how `filename` was used because `filename` has an extension. I initially missed `filename[0:-4]` . may i suggest `os.path.splitext()` instead? I say that from experience when my file had .hdf4 instead .hdf as the extension :-/

Also good to know I need `filename` and `path` for these scripts.  I didn't use readimage() because my file needs to be debayered first. I could contribute a new function or would you rather see it inside `readimage`?

**Comment by nfahlgren** [comment]
Cool, splitext is a great idea. I have worried about coming across a `.jpeg` at some point :)

It would be awesome if you added a function for reading raw bayer images. I would say for now a separate function would be easiest. If we ended up having a bunch of different "read" functions we might be able to add a higher level one that autodetects the input type and calls the appropriate function, or something like that.

**Comment by dschneiderch** [comment]
@nfahlgren  I created a new function for reading bayer images but I'm not sure how to test it.... sorry still figuring out how python works. I reran `python setup.py install` in my local plantcv directory but the function wasn't available when I restarted python and loaded plantcv. The installation seems to have been successful. can you help?
here is the function: https://github.com/dschneiderch/plantcv/blob/readbayer/plantcv/plantcv/readbayer.py

**Comment by nfahlgren** [comment]
@dschneiderch, no worries, this is awesome! In order to make the function available after import you have to add it to the `__init__.py` file one directory up: https://github.com/dschneiderch/plantcv/blob/readbayer/plantcv/plantcv/__init__.py
