### ISSUE TITLE
Naive Bayes Multiclass CV2 error

### ISSUE THREAD

**Issue by owaisahmed3** [danforthcenter/plantcv#281]
### Description

I am new to plantcv. Very interested to learn and use this into my project. I have built and ran the VIS tutorial on my system.
I am using:
Ubuntu 18.04
Python 3.6.5
Opencv 3.4.1

However i am unable to run the machine learning tutorial, naive bayes multiclass part is where i am stuck at.
I am making a text file as it is given in the tutorial with four classes. Got over the singular matrix error by tab spacing, but i am getting this error:
Starting run 2018-12-11_17:47:50

Running the naive Bayes multiclass training method...
OpenCV(3.4.1) Error: Assertion failed ((scn == 3 || scn == 4) && (depth == 0 || depth == 5)) in cvtColor, file /home/ofl/opencv-3.4.1/modules/imgproc/src/color.cpp, line 11214
Traceback (most recent call last):
  File "plantcv-train.py", line 88, in <module>
    main()
  File "plantcv-train.py", line 83, in main
    options()
  File "plantcv-train.py", line 51, in options
    args.func(args)
  File "plantcv-train.py", line 73, in run_naive_bayes_multiclass
    plantcv.learn.naive_bayes_multiclass(samples_file=args.file, outfile=args.outfile, mkplots=args.plots)
  File "/home/ofl/Downloads/working/plantcv/machine/plantcv/learn/naive_bayes.py", line 136, in naive_bayes_multiclass
    hsv_img = cv2.cvtColor(bgr_img, cv2.COLOR_BGR2HSV)
cv2.error: OpenCV(3.4.1) /home/ofl/opencv-3.4.1/modules/imgproc/src/color.cpp:11214: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cvtColor

Command is:
python plantcv-train.py naive_bayes_multiclass --file pixel_samples.txt --outfile naive_ayes_pdfs.txt --plots

If there is anything i am doing wrong, i will be thankfull if someone here guides me through this.

**Comment by nfahlgren** [comment]
Hi @owaisahmed3, thanks for providing this detailed description, it's really helpful! Could you upload your `pixel_samples.txt` here by dragging and dropping it into the comment box?

**Comment by owaisahmed3** [comment]
[pixel_samples.txt](https://github.com/danforthcenter/plantcv/files/2670602/pixel_samples.txt)
Thank you for responding. Here is the pixel_samples.txt file.

**Comment by nfahlgren** [comment]
Thanks @owaisahmed3. It looks like the error you are seeing is because the first two columns of the header row have two tab characters separating them. This causes the program to think there are two extra columns.

After removing the extra spaces I get the error `numpy.linalg.linalg.LinAlgError: singular matrix` which indicates that there are not enough pixel samples (rows). There's no hard rule for how many pixels need to be sampled but the Kernel Density Estimator needs some minimum amount of data and variability to create the Probability Density Functions. We typically have 100s-1000s of sampled pixel values. If you are using the ImageJ pixel inspector tool it grabs nine or more pixels at once depending on what you set the inspector box size to, so it doesn't take long to grab a lot of samples. Note that you don't have to have the same number of pixel samples for each class (column). As long as each cell is separated by a tab the program will ignore empty cells.

**Comment by owaisahmed3** [comment]
Thanks @nfahlgren. I have removed the extra tabs in first column also and am getting the same error now. `numpy.linalg.linalg.LinAlgError: singular matrix`. Just for the sake of running the script i copied and pasted same values for multiple times and still the error remains the same. I can capture the pixel values from ImageJ tool as described in tutorial also. I will also try and make a new file with my captured values. Thank you for the help, i will update here soon.

**Comment by owaisahmed3** [comment]
It worked after getting 100 samples of pixels by using ImageJ. Thank you for guidance. Next step is pseudocolored image. I was wondering if there is any way that we can automate this long process of getting pixel samples from image.

**Comment by nfahlgren** [comment]
Hi @owaisahmed3, glad it's working! Because this is a supervised machine learning approach there's no way to bypass the need for the training data. We don't have any unsupervised approaches implemented in PlantCV currently but that could theoretically be one way to automate the process.

For pixel sampling in ImageJ, not sure if this helps but you can change the size of the pixel inspector region to grab more pixels in one click.

When you click a region the pixel inspector box will pop up:
![screen shot 2018-12-13 at 10 53 56 am](https://user-images.githubusercontent.com/6233508/49956372-a206be80-feca-11e8-81d3-70e1d377f0a4.png)

The select the "Prefs" box in the upper left and change the Radius:
![screen shot 2018-12-13 at 10 54 12 am](https://user-images.githubusercontent.com/6233508/49956449-cebad600-feca-11e8-855e-74aaf59d4db8.png)

**Comment by nfahlgren** [comment]
Closing for now but feel free to reopen if needed!
