### ISSUE TITLE
plotting images from fluor_fvfm.py

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#306]
I'm futzing with adding custom cmap arguments to the plotting routines; see cmap branch.
This was in part motivated by differences in colormap between debug='plot' and 'print'

But I've come across some confusing behavior specifically in fluor_fvfm.py. 

1. the svg colorbar does not update if it is already present because you are checking for the file. i'd propose rewriting it regardless if it exists since there is no way to check if the cmap is the same.

ACTION: remove `if not os.path.isfile(os.path.join(path, fig_name)):`

2. more critically, if debug = 'plot' then the histogram gets messed up. maybe there is a figure counter missing...i'm not sure how this works exactly. see attached image.

<img width="401" alt="test_fvfm_hist" src="https://user-images.githubusercontent.com/7461221/51699137-d2a94000-1fc0-11e9-9806-05fbd91fe884.png">

ACTION: help needed

3. the filename argument for fluor_fvfm is confusing. looks like it can be a path or filename with or without extension. for most of the output figures (pseudo_fvfm, fvfm_hist, and fv_img), a filename of "test" becomes the prefix e.g. "test_pseudo_fvfm.png" but the code suggests you are expecting a directory too? at the moment it just gets saved in my working directory.
confusingly, the FvFm_pseudocolor_colorbar is saved without the prefix in the root project directory. can we add the prefix? could we also create the directory if it doesn't exist? updating the input description to specify path and filename where the path already exists would probably be helpful too.

ACTION: at least clarify input description. add prefix to colorbar svg ?

4. Would it be an issue for any masking functions/lines to replace masked pixels with np.nan instead of 0? this would make colormaps more intuitive, e.g. with using the hsv colormap.

![test_pseudo_fvfm](https://user-images.githubusercontent.com/7461221/51699580-ef924300-1fc1-11e9-93e9-7490821ca6f9.png)

ACTION: replace 0 with np.nan across the package

5. I made changes to printing functions to accept a cmap argument. I used viridis as the default in line with some of the other functions. hope that is good? better than jet or hsv IMHO.

ACTION: no more required if acceptable.

6. lastly, i extended the cmap changes to analyze_NIR_intensity and mapped matplotlib cmap argument to a opencv colormap. currenlty only viridis and jet (the previous default). However, I don' t have a NIR image atm to check the behavior so if someone could test this that would be awesome!

ACTION: help needed to test that changes didn't break the function.

**Comment by HaleySchuhl** [comment]
I can hopefully be helpful for parts 2 and 6! We have recently added interactive documentation that might be useful.

There is a PSII tutorial here that is working with debug='plot':
<https://mybinder.org/v2/gh/danforthcenter/plantcv-binder.git/master?filepath=notebooks/psII_tutorial.ipynb>

You can download images that can be used with `pcv.analyze_nir_intensity` here:
<https://mybinder.org/v2/gh/danforthcenter/plantcv-binder.git/master?filepath=notebooks/img/tutorial_images/nir>

These links usually take 30-60 seconds to load (and in the meanwhile you'll see a 404 error).

**Comment by nfahlgren** [comment]
@dschneiderch, @HaleySchuhl and I were thinking about a couple updates to address #307, #309, #310, and #311.

The first is pretty straightforward. Our thought is that the method for plotting/printing a grayscale image with a colormap can be modularized. We can develop a function that can take a grayscale image, an optional mask, and a colormap. This function can incorporate the `np.nan` idea so that the background is kept black regardless of the colormap. Or alternatively we could set a background color with an option that takes "black" or "white" as input. It can also include the colorbar in the image. This function would allow us to reuse the same method for PSII, NIR, Thermal, or any user-supplied grayscale image.

The other thought was that maybe having the `analyze_*` functions with the `filename` arguments is not the way to go. What if we returned the images, plots, etc. and let the user save them with the `pcv.print_image()` function? That gives the user the ability to save the images where ever they want with whatever name they want.

**Comment by dschneiderch** [comment]
👍  returning the images for the user to save. It's an extra step for the user, but it will give the ability to make customized figures for whatever the user needs. since i'm working with different people all the time rather than running my own experiments, I'm finding everyone has a different idea how their plots should look. some want the hsv colormap that Walz uses although I try to discourage  it for something more sensible. However, it would still be convenient you could provide a method within print_image for each image type that has sensible defaults, nan for the background, and the ability to choose the color map.
let me know how I can help.

**Comment by nfahlgren** [comment]
I think all of these issues are now address, but please reopen if anything isn't working as expected!
