### ISSUE TITLE
Implement method for users to specify the colormap to use for pseudocolored images

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#311]
### Description

From #306:

@dschneiderch:
> I made changes to printing functions to accept a cmap argument. I used viridis as the default in line with some of the other functions. hope that is good? better than jet or hsv IMHO.

>Lastly, I extended the cmap changes to analyze_NIR_intensity and mapped matplotlib cmap argument to a opencv colormap. currenlty only viridis and jet (the previous default). However, I don' t have a NIR image atm to check the behavior so if someone could test this that would be awesome!

Any solution here would probably also apply to the upcoming thermal analysis function. Any others?

### Completion Criteria

Merge pull request from https://github.com/dschneiderch/plantcv/tree/cmap or an alternate solution.

**Comment by HaleySchuhl** [comment]
Analyze* functions in PlantCV no longer print or return pseudocolored images. Instead, to give more control to the user we added `pcv.pseudocolor`, which allows user to specify any matplotlib colormap, provide a mask, limit maximum and minimum pixels values, and it always plots the color bar.

**Comment by dschneiderch** [comment]
sorry to be the bearer of bad news but there seems to be a figure overwriting issue with this function.
In the screenshot below, check out the result of the 3 plotting calls from pseudocolor:

![image](https://user-images.githubusercontent.com/7461221/53260131-a0edcc80-3685-11e9-9280-78b2c426cddf.png)

I would expect
1. one color bar (so basically a whole new figure)
2. I expected the min and max of the color bar to be that of the min_value and max_value arguments.

**Comment by dschneiderch** [comment]
Expanding on 2.
It looks like a plt.clim() actually scales the image colors too. I'm looking just to have comparable scales on the colorbar so that you can compare across images that might have different min/max values.  I don't think lopping off the top/bottom of the data is the right way to go.

So I guess I'm just expecting the color->value mapping to controlled rather than the value itself. 
I don't want to stretch the range in the image from 0.2-0.6 to 0-1 but rather map the valuess to a consistent range of colors. 

Does this make sense? 
- The ticks need to be set. This is could be difficult to get right if you don't  know what range people are going to use it with. Maybe just let people set tick labels?
- How do you tell matplotlib the range within which to scale the colors without stretching the range?

**Comment by HaleySchuhl** [comment]
Thanks @dschneiderch for bringing this to our attention! I had been testing in Jupyter and hadn't come across this bug since I would run it in separate cells. I fixed this overwriting issue and added it to #330. As for your second point, I'm not sure I totally understand what you're looking for. I added `min_value` and `max_value` per request of someone at Danforth that is using the function. But I can look into options for colorbars in matplotlib and see if there's a way to limit range in a different way.

**Comment by dschneiderch** [comment]
I was just writing this, but  the colorbar issue only happens if params.debug = 'plot'

**Comment by dschneiderch** [comment]
The current implementation for min_value and max_value is to chop off the bottom/top of the values. I don't think lopping off the top/bottom of the data is the right way to go. What if my max value is less than `max_value` ? As a user I'd still expect the color range from min_value to max_value.

**Comment by HaleySchuhl** [comment]
Yes, and while reproducing the bug I found that the function had been plotting to the screen in Jupyter while `pcv.params.debug='print'` or `pcv.params.debug=None` so I've adjusted this as well. 

It looks like `vmax, vmin` inside `plt.imshow()` is what you're looking for! I can add this to the pseudocolor pull request. https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html

**Comment by dschneiderch** [comment]
Ok I agree. 
`plt.clim(vmin=,vmax=)` also gives the same result.

Specifying vmin and vmax will give the same result as your current pull request IF there are values larger than max_value (and less than for vmin etc). If the max data value is less than max_value then specifying vmax still lets you scale the colorbar to your desired range. Better than modifying the data!
Thanks for your patience! I was a bit confused over here 🙄
