### ISSUE TITLE
Add pseudocolor function options 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#329]
### Description
Since `pcv.pseudocolor` is a plotting function we can add more options to the user. 

### Details
* Users are already able to able to choose the type of background (provided they supply a mask), choose their preferred colormap, limit the range of interest for pseudocoloring, auto-crop the plot to the object of interest (provided they supply a single or grouped contour), whether or not the axes are plotted.
* Additional options that we could add include the option to remove the color bar and remove the title.
* Make it so that if the axes are turned off then the title is removed too. 
* Provide defaults so those users that don't have a preference don't have to worry about the additional parameters. 
* Other options?? 

### Completion Criteria
- [ ] Discuss and add other options
- [ ] Add the options
- [ ] Write tests for new options 
- [ ] Update documentation (including more images) 
- [ ] Add to the package (pull request)

**Comment by dschneiderch** [comment]
Testing things out and I find it confusing that the debug "print" for pseudocolor saves it in the working directory by default instead of in params.debug_outdir. It would be more consistent in debug_outdir. I think we shouldn't conflate a debug print statement with a user print statement, if that makes sense. They serve two different purposes. Theoretically when you are running a pipeline you might set debug=None, but you'd still want to print a nicely pseudocolored image as part of your output. Personally I would make `path` a required argument with no default (and which would include the filename because #_pseudocolor.png isn't very descriptive for a real output).

The function returns pseudo_img suggesting that the user can then do what they wish with it. I think that's great in case things need to be tweaked. But if debug='print' or 'plot' or None (all 3!) the pseudo_img axes are actually cleared so the function now returns an empty Figure. Why return the Figure handle?
You could change it so if debug=None then the figure is not cleared and closed and the returned figure has axes as expected. However, then you rely on the user to know that they need an if statement 
```
myfig = pseudocolor(....)
if pcv.params.debug == None:
    myfig.savefig('output/figs/myfig.png')
```
I think is probably too much to ask for the average user. Perhaps there is a more optimal solution?

PS I will be off the grid for the next 5 days if you continue this discussion.

**Comment by HaleySchuhl** [comment]
Thanks @dschneiderch for bringing this up! The `pcv.params.debug = None` changes I made in an attempt to stop matplotlib from plotting to the screen also cleared the figure I was trying to return. I've updated #330 so that it'll return the figure regardless of debug mode. 

 My thinking with the `path` argument was that a user could always set `path=params.debug_outdir` or `path=args.outdir` in the following example: 

```
class options:
    def __init__(self):
        self.image = "/home/hschuhl/colormap/original_image_vis.jpg"
        self.debug = "plot"
        self.writeimg= False
        self.result = "./vis_tutorial_results"
        self.outdir = "./vis_tutorial_results"
        
# Get options
args = options()

# Set debug to the global parameter 
pcv.params.debug = args.debug

# Read image in 
img, path, filename = pcv.readimage(args.image)``` 

Since the figure is returned by the function, a user can specify where the image gets saved and change the filename to be more specific (and include the original image filename if they want) with `pcv.print_image`. This is what we expect to be the case most of the time since jobs run in parallel are likely going to have `pcv.params.debug = None`, thus `#_pseudocolor.png` wouldn't get printed out. My thinking was that `pcv.params.debug='print'` would really just get used for debugging, so having `path` default to the current working directory instead of being required would make it simpler to use. I think it would also be a little unusual to have `path` be required when it isn't used when debug is plot or None.

**Comment by dschneiderch** [comment]
The problem I'm finding is 
1. I  have 3 *pseudocolored.png files being saved, with no indication which is which. Current me knows that the order of the numbers corresponds to the order in the script but that is confusing long-term and not helpful to others. Are you expecting the user to rename these if they want to keep them as long-term output?
![image](https://user-images.githubusercontent.com/7461221/53666782-e8470080-3c23-11e9-8874-86a6feecab5f.png)

In order to effectively use the pseudocolor image as an "output" I need to be able to save and identify the file. I would like to save a greenness index image to provide users with their results.

> We could always change the default from the current directory to `debug.outdir` though since it's default is already `'.'`.

This would make the most sense to me and would work well if the user (like me) defines `debug_outdir` at the start.

Since pseudocolor doesn't return an image if debug = 'print', I changed debug = None and got this as the output from `gi_img.savefig()`:
![image](https://user-images.githubusercontent.com/7461221/53689375-397cf000-3d09-11e9-98dd-2287766a3be0.png)


There are two issues in this figure. 1. the colorbar is overwriting on the  previous figure. 2. the background of the image is not being masked white as I asked for.  Only 2 is an issue in the debug output:
![137_pseudocolored](https://user-images.githubusercontent.com/7461221/53689426-7a293900-3d0a-11e9-973b-0d97109a8e66.png)


Here is the code I ran where fn is the filename of the .tif.

    img,_,_ = pcv.readbayer(fn) #read image
    mask = createmasks.vismask(img,radius,xstart,ystart,xadj,yadj)
    img_masked = pcv.apply_mask(img,mask,'black')

    plant_area = np.sum(np.logical_and(img_masked!=0, img_masked!=255))

    b,g,r = cv2.split(img)

    pcv.pseudocolor(r, cmap='Reds', background='white',min_value=0, max_value=255, mask=mask, axes=False, path = pcv.params.debug_outdir)
    pcv.pseudocolor(g, cmap='Greens', background='white', min_value=0, max_value=255, mask=mask, axes=False, path = pcv.params.debug_outdir)
    pcv.pseudocolor(b,cmap='Blues', background='white', min_value=0, max_value=255, mask=mask, axes=False, path = pcv.params.debug_outdir)

    g_masked = np.ma.array(g,mask=~mask.astype(np.bool)).astype('uint16')
    r_masked = np.ma.array(r,mask=~mask.astype(np.bool)).astype('uint16')
    b_masked = np.ma.array(b,mask=~mask.astype(np.bool)).astype('uint16')

    denom = (g_masked + r_masked + b_masked)

    # pcv.pseudocolor(denom,cmap='viridis',min_value=0, max_value=255*3, path=pcv.params.debug_outdir)
    gi = np.divide(g_masked, denom, where = denom!=0)

    gi_img = pcv.pseudocolor(gi,cmap='viridis', min_value=0.2, max_value=0.7 , mask=mask, background='white', path=pcv.params.debug_outdir)
    gi_img.savefig(os.path.join('output','vis', outfn + '_greenness.png'), bbox_inches='tight')

**Comment by dschneiderch** [comment]
this may have resolved itself with a windows restart. i'm not sure why.

**Comment by nfahlgren** [comment]
@dschneiderch I think @HaleySchuhl is going to remove the `path` option as it is being used to set the output location when `debug = "print"` and instead we will use the location set by `pcv.params.debug_outdir` as we do with other functions.

The output names of images saved with `debug = "print"` are not meant to be informative other than the order in which they are created. Our intension for images saved with the debug option to be used only for debugging. 

The `pcv.pseudocolor` function (and other analysis functions) returns the image so that the user can save it to a location they want with an informative name should they want to keep the image. Does that all make sense?

We are also trying to track down the issue with white backgrounds. It seemed to be working for me but @HaleySchuhl found that it was behaving like you are seeing, so we're trying to work out why there is an inconsistency (might just be me messing things up of course).

**Comment by nfahlgren** [comment]
@HaleySchuhl I just tested the `background = "white"` on my machine again and I get a black background, so I think your fix is correct. Not sure what I was doing before!

**Comment by dschneiderch** [comment]
> The output names of images saved with debug = "print" are not meant to be informative other than the order in which they are created. Our intension for images saved with the debug option to be used only for debugging.

> The pcv.pseudocolor function (and other analysis functions) returns the image so that the user can save it to a location they want with an informative name should they want to keep the image. Does that all make sense?

Yes - I think I wrote that because I wasn't getting a return image when `debug = "print"` but that's resolved now, right?

**Comment by HaleySchuhl** [comment]
@dschneiderch, definitely let us know if the function isn't returning an image under `debug='print'` but I believe it is resolved. I wasn't able to reproduce that when I was testing yesterday.
