### ISSUE TITLE
Output files going to three different locations

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#331]
I have developed a visible imaging analysis pipeline Python script to analyse a folder containing a series of PNG images. The script is called on a Windows machine as follows:

`C:/Path/To/plantcv-pipeline.py -d C:/Path/To/projects/plantcv-vis/img/dataset -a filename -p C:/Path/To/projects/py/VIS_Optimised_Pipeline.py -i C:/Path/To/projects/img/dataset/output -s C:/Path/To/projects/sql/sql3.sql -f id_other_timestamp -t png -T 16 -w`

The analysis seems to be working fine, but I am obtaining output in multiple locations:
- plantcv_NoneNone_*.tab and plantcv_NoneNone*.log files in the current directory used to call the script.
- A folder of plantid_timestamp.txt files in a subdirectory of the current directory used to call the script (for example, /2019-02-22_16-24-33 
- Image output in the folder specified by `-i` (eg boundary, mask, pseudocolour images etc).
- Entries in the SQL database specified in `-s`

My question is: How can I get all of those files (except the SQL entries) to be dumped in `-i`? I would have thought that all output would go to the location specified by the `-i` flag. I cannot figure out how to change this or whether it is a bug?

**Comment by nfahlgren** [comment]
Hi @AdamDimech, the -i flag only controls where image output goes, everything else is currently written to the working directory.

The time stamped folder contains temporary files (the outputs of your PlantCV script for each image). These can be helpful for debugging but can otherwise be deleted.

The other text files are logs (*.log) or tabulated output (*.tab). The tabulated output files are used to populate the SQLite database. Therefore the data you want for downstream analysis can either be read from the database or from the tab-delimited files.

**Comment by AdamDimech** [comment]
Is there a way to have PlantCV write those files to the location specified in `-i`? I have tried to use [shutil](https://docs.python.org/3/library/shutil.html) to move the files post-analysis but with no luck so far.

**Comment by nfahlgren** [comment]
The options `-d` and `-i` control where permanent outputs go, not sure we want to also put the temporary output files (.log, .tab, and timestamped directories) into the output image directory. In principle we could have `plantcv-pipeline.py` delete the temporary files but I have always figured it is safer to let the user delete them in case something goes wrong during a run, since it can take several hours to analyze a large dataset.

We are planning on rebuilding the parallelization process soon, see the last section of #304. Looks like I don't have an issue for this yet, but the plan is to use [Nextflow](https://www.nextflow.io/) as the parallelization engine so that jobs can be distributed on a cluster instead of limited to a single machine (though Nextflow supports that type of execution too).

**Comment by HaleySchuhl** [comment]
With enhancements (#366 ) to the parallelization tools (now plantcv-workflow.py) data gets stored to a single .json file and most temporary files are gone apart from a single log.
