### ISSUE TITLE
read_array discussion (thermal)

### ISSUE THREAD

**Issue by maliagehan** [danforthcenter/plantcv#359]
### Description
FLIR data is output as .csv and needs to get read in differently than other images since cv2.imread (which is used for supported `pcv.readimage()` modes gray, rgb, and rgba). Downstream steps for processing thermal data, such as `pcv.analyze_thermal_values`, should be formatted as an array.  

### Completion Criteria

- [ ] Discuss and develop requirements docs
- [ ] Create completion criteria for next steps

**Comment by HaleySchuhl** [comment]
After updating `pcv.analyze_thermal_values()` yesterday to be compatible with the current PlantCV version and eliminate redundancy with `pcv.visualize.pseudocolor()` the only inputs required to collect thermal value data (histogram and summary stats) are the thermal values as an array and a mask. The scaled array image isn't needed, and upon testing it appears that pseudocoloring is already compatible with the unscaled thermal values as an array. 

**Are there other reasons to create a scaled array image?** Testing with `pcv.plot_image()` scales the image in a way that it's definitely visible in Jupyter since in the source code it's using `plt.imshow`. Would have a need to use `pcv.print_image(unscaled_thermal_array, filename)` or would it be sufficient to provide an example to create a scaled image? 
```
scaled_thermal = pcv.visualize.pseudocolor(gray_img=unscaled_thermal_array, 
    min_value=pcv.outputs.observations['min_temp']['value'], 
    max_value=pcv.outputs.observations['max_temp']['value'] )
```

**I suggest that we add mode "FLIR" to `pcv.readimage()`** and return the thermal array, path, and filename as we do with other options for this function. We can have a separate function to scale thermal arrays if useful to avoid changing the number of objects getting returned by `pcv.readimage()`
