### ISSUE TITLE
Invalid contour + displaying work

### ISSUE THREAD

**Issue by scsolano** [danforthcenter/plantcv#368]
### Description

 Hello again!

 I am trying to get through my pipeline and I have two concerns

 My first: whenever I get to the step where I want to combine the identified objects and the actual image, I get an "Invalid contour" warning. It doesn't necessarily say that it doesn't compile, it just throws an error and I can continue although I'm sure future work would have some issue because of the invalid contour error. These issues came up in #66 and #233, but I don't get any warning with the ROI like they did ("Make sure ROI is COMPLETELY in frame or object detection will not perform properly"), so its probably something else going on.

 My second: how do I display the work that I am doing on Jupyter using the pcv.plot_image function? I know it sounds kind of weird, but I want to get a visual on every step that I am doing to ensure that what I am doing works. Like how "pcv.plot_image(s_fill)" displays the thresholded image after filling in speckles, I would like to do the same for the ROI and object detection, but since I have several things going on in some steps I'm not too sure what to input in pcv.plot_image. For step 9 below, I tried things like "pcv.plot_image(id_objects)" and "pcv.plot_image(id_objects, obj_hierarchy)" and neither worked out. "pcv.plot_image(obj_hierarchy)" gives me an error too, so I'm not sure what I'd need to input in plot_image to display the work on step 9 and beyond.

 I'll post my pipeline script below (still in progress as I need to parallelize and put the ML part) for detail because I don't have any idea where to pinpoint this issue within the script (if I'm missing anything). I apologize if these questions seem kind of weird, I'm still learning to get the general grasp of PlantCV

 Thank you in advance!

### Details

import sys
import plantcv
%matplotlib inline
import os
import numpy as np
import cv2
from matplotlib import pyplot as plt
from plantcv import plantcv as pcv

#Step 2: Global variables
device = 0 
debug = 'plot' 
rgb_img = 'C:\\Users\\sccs9\\Pictures\\105_180_3.JPG'

#Step 3: Read RGB image
img, path, filename = pcv.readimage(rgb_img)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.show()

#Step 4: Correct image 
corrected_img = pcv.white_balance(img)

#Step 5: RGB colorspace to HSV colorspace
s = pcv.rgb2gray_hsv(img, 's')
pcv.plot_image(s)

#Step 6: Set a binary threshold
s_thresh = pcv.threshold.binary(s, 150, 255, 'light')
pcv.plot_image(s_thresh)

#Step 7: Fill in small objects
s_fill = pcv.fill(s_thresh, 300)
pcv.plot_image(s_fill)

#Step 8: Dilate 
dilate_img = pcv.dilate(s_thresh, 1, 1)
pcv.plot_image(dilate_img)

#Step 9: Find objects 
#This is where I don't know how to use pcv.plot to show the objects within the image
id_objects, obj_hierarchy = pcv.find_objects(img, dilate_img)

#Step 10: Define region of interest (ROI)
roi_contour, roi_hierarchy = pcv.roi.rectangle(x=100, y=100, h=200, w=200, img = img)

#Step 11: Keep objects that overlap with the ROI
roi_objects, roi_obj_hierarchy, kept_mask, obj_area = pcv.roi_objects(img, 'partial', roi_contour, roi_hierarchy, id_objects, obj_hierarchy)

#Step 12: Combine objects
#This is where I get "invalid contour"
obj, mask = pcv.object_composition(img, roi_objects, roi_obj_hierarchy)

**Comment by nfahlgren** [comment]
Hi @scsolano!

One quick thing I want to suggest answers the second part of your question but might help with the first part since it will help you visualize what's going on for each step.

You can globally turn on the plotting mode so that (almost) every function will output image(s) to visualize the step. You can change your global variables section like this:

```python
#Step 2: Global variables
pcv.params.debug = 'plot'
rgb_img = 'C:\Users\sccs9\Pictures\105_180_3.JPG'
```

You can also use `pcv.plot_image(img)` any time, it should display the image even if `pcv.params.debug` is set to other values such as `None` or "print".  You should not have to use pyplot, but you can of course!

Let us know if plotting is not working. Hopefully the plots will help with figuring out the object composition problem but we're happy to help with that also. The most common reason that object composition would fail is when the previous step outputs no contours (i.e. `roi_objects` is empty).

**Comment by HaleySchuhl** [comment]
Hi @scsolano ,

Would it maybe be the case where the ROI was completely inside the outermost contour of your object? This came up in #435 and would possibly lead to the error message that you were getting. I'd suggest turning debug mode to 'plot' as Noah suggested, and also update the version of PlantCV that you're using since we have fixed some buggy situations. 

If you continue to run into errors or have any questions related to this workflow please feel welcome to reopen this issue!
