### ISSUE TITLE
Develop issues and pull request templates

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#37]
I think these templates are useful, see: https://github.com/terraref/computing-pipeline/tree/master/.github

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/167498468031290/171889363053252)

**Comment by jshoyer** [comment]
Specifying templates is simply a matter of putting files (ISSUE_TEMPLATE[.md], PULL_REQUEST_TEMPLATE, and/or CONTRIBUTING) into a top-level `.github` directory (or the project root), as in the repo you link to.

Were you planning on adapting the NCSA templates? I think it would be fine to just use them unchanged.

More details on creating the three files (through the gh web interface): https://help.github.com/articles/helping-people-contribute-to-your-project/

**Comment by nfahlgren** [comment]
Yep, I was thinking about using them pretty much as is. I added a new CONTRIBUTING.md already, but it (and the other templates) won't take effect until we merge with master. Unless putting them in .git will bypass the branches?

**Comment by jshoyer** [comment]
Lots of exciting progress towards the 2.0 release recently!

`<bikeshedding>`
Perhaps it would be worth switching from dev-branch-based development to trunk-based development shortly before or after that major release. I suggest this mainly because github is so `master`-centric (project landing page. network graph page, etc.)

Deciding whether or not to change the development model depends of course on how stable you want the 2.0 branch to be, when you expect it to go stale, etc.
`</bikeshedding>`
