### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#392]
I have been running PlantCV workflows over a [flat directory of images](https://plantcv.readthedocs.io/en/latest/pipeline_parallel/#running-plantcv-workflows-over-a-flat-directory-of-images). I recently upgraded PlantCV to Version 3.4.0 and am now experiencing problems writing to the JSON file (not withstanding my [other problem](https://github.com/danforthcenter/plantcv/issues/391)).

I have reviewed the latest [VIS tutorial](https://plantcv.readthedocs.io/en/latest/vis_tutorial/) code (and made changes to [my code](https://gist.github.com/AdamDimech/e54fe95f7face972192fbd76fa83bf9a)) and get the following error:

`Traceback (most recent call last):
  File "C:\Path\To\plantcv_pipeline.py", line 262, in <module>
    main()
  File "C:\Path\To\plantcv_pipeline.py", line 247, in main
    pcvp.process_results(valid_meta=args.valid_meta, job_dir=args.jobdir, json_file=args.json)
  File "C:\Path\To\plantcv_pipeline.py", line 42, in process_results
    obs = json.load(results)
  File "C:\Anaconda\envs\plantcv\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Anaconda\envs\plantcv\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda\envs\plantcv\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda\envs\plantcv\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I have not created a JSON file in advance, but have made the directory for it. I have added and subtracted the `-c` flag.

My command is as follows:
`C:/Path/To/plantcv/plantcv-workflow.py -d "G:/Path/To/Images/" -a filename -p C:/Path/To/plantcv_pipeline.py -i "G:/Path/To/Images/Output" -j "G:/Path/To/Images/Output/json/results.json" -f id -t JPG -T 16 -w -c`

When PlantCV used SQL files (and the `-s` flag), a new SQL would be created if one wasn't present already.

Where have I gone wrong?

**Comment by HaleySchuhl** [comment]
Thanks for posting the descriptive issue @AdamDimech ! We have also run into this bug. There is a flaw with the data output that was modified in PlantCV v3.4. If no data gets collected, or if any of the images experience a fatal error during the image analysis pipeline it will break the line 42 of `process_results.py` that is `obs = json.load(results)` and prevent the output .json file from getting created at all. This is problematic since metadata also gets stored to the data output file, and should get stored regardless of any analysis functions getting used (for example a user could have a workflow that outputs images without collecting observations about shape/color/etc). We also need to store measurements collected even if one or more images fail. 

We expect to have a solution to this bug pretty soon since @nfahlgren is already working on this update. Additionally, he is working on a function to convert the PlantCV data output into a table that can be used in R, Excel, and so forth more easily.
