### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_cv2)

### ISSUE THREAD

**Issue by RavinduDharmasena** [danforthcenter/plantcv#397]
### Details
I'm running the plantCV on a conda distribution and it is using python 3.7.3 and django 2.2.1. when I am running the python script included in the zip file it will throws the error given below.

Image and python script that I used in this scenario is given below.
[Test_NIR_1.zip](https://github.com/danforthcenter/plantcv/files/3309304/Test_NIR_1.zip)

`Traceback (most recent call last):
  File "testNIR.py", line 4, in <module>
    import cv2
ImportError: dynamic module does not define module export function (PyInit_cv2)` 

The command that I executed is 
python testNIR.py -i ./IMG_8764_RGB.jpg -o ./output -D -r ./output/nir_data.txt

PS : When I searched on the internet I found that it is an openCV also connected with this issue. Here is the link of that stackoverflow page. (Just a tip. I don't know whether it is related with this issue).

[https://stackoverflow.com/questions/39112321/python-3-5-importerror-dynamic-module-does-not-define-module-export-function-p](url)

**Comment by HaleySchuhl** [comment]
Hello @RavinduDharmasena ,

I haven't come across this error before. Could you run `pip freeze` in the command line and post the output here? 

It sounds like your PlantCV conda environment might be broken since you were able to run a similar NIR workflow before. We have instructions on how to remove a broken environment [here](https://plantcv.readthedocs.io/en/latest/installation/) on the PlantCV documentation which might take of this import error.

**Comment by RavinduDharmasena** [comment]
@HaleySchuhl, This is the output I get when after executing the `pip freeze`. 

`ravindu@ravindu-Samsung-DeskTop-System:~$ pip freeze
adium-theme-ubuntu==0.3.4
alabaster==0.7.7
appsettings==0.8
attrs==15.2.0
autobahn==0.10.3
Babel==1.3
bzr==2.7.0
catkin==0.6.16
catkin-pkg==0.4.12
catkin-pkg-modules==0.4.12
chardet==2.3.0
cloudpickle==0.8.1
configobj==5.0.6
cryptography==1.2.3
cycler==0.9.0
decorator==4.0.6
defusedxml==0.4.1
docutils==0.12
ecdsa==0.13
ecto==0.6.11
empy==3.3.2
enum34==1.1.2
ExifRead==2.1.2
futures==3.0.5
GDAL==2.1.3
gippy==1.0.0
gpxpy==1.3.5
httplib2==0.9.1
idna==2.0
ipaddress==1.0.16
ipython==2.4.1
Jinja2==2.8
keyring==7.3
launchpadlib==1.10.3
lazr.restfulclient==0.13.4
lazr.uri==1.0.3
loky==2.4.2
lz4==0.7.0
MarkupSafe==0.23
matplotlib==1.5.1
mercurial==3.7.3
mpi4py==1.3.1
msgpack-python==0.4.6
netifaces==0.10.4
networkx==1.11
nose==1.3.7
numpy==1.16.3
oauth==1.0.1
PAM==0.4.2
pandas==0.24.2
paramiko==1.16.0
pexpect==4.0.1
Pillow==3.1.2
psutil==5.6.2
ptyprocess==0.5
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycurl==7.43.0
pydot==1.0.29
Pygments==2.1
pygobject==3.20.0
pygpgme==0.3
PyOpenGL==3.0.2
pyOpenSSL==0.15.1
pyparsing==2.0.3
pyproj==2.1.3
pyserial==3.0.1
Pyste==0.9.10
python-apt==1.1.0b1+ubuntu0.16.4.2
python-dateutil==2.8.0
python-snappy==0.5
pytz==2019.1
PyYAML==5.1
pyzmq==18.0.1
repoze.lru==0.7
roman==2.0.0
rosdep==0.15.1
rosdistro==0.7.4
rosdistro-modules==0.7.4
rosinstall==0.7.8
rosinstall-generator==0.1.16
rospkg==1.1.9
rospkg-modules==1.1.9
scipy==1.2.1
SecretStorage==2.1.3
service-identity==16.0.0
Shapely==1.6.4.post2
simplegeneric==0.8.1
simplejson==3.8.1
six==1.12.0
Sphinx==1.3.6
sphinx-rtd-theme==0.1.9
trollius==2.0.1
Twisted==16.0.0
txaio==1.0.0
unity-lens-photos==1.0
vcstools==0.1.40
wadllib==1.3.2
wstool==0.1.17
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xmltodict==0.12.0
zope.interface==4.1.3
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

Now I'm using plantcv in a conda environment in Ubuntu LTS 16.04.6 OS. But when I am creating previous issue I was doing same thing in Windows 10 Home OS.

**Comment by nfahlgren** [comment]
Hi @RavinduDharmasena, could you try running `python` on the command-line to open a Python console. Then in the console run: `import cv2` and see if you get the same error above.

**Comment by RavinduDharmasena** [comment]
Hi @nfahlgren, This is the output I got after executing your instructions

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_cv2)`

Looks like it is the same error.

**Comment by nfahlgren** [comment]
For some reason OpenCV is not installing correctly then. Could you try creating a new environment as a test? You could run: 

```bash
conda create -n test py-opencv=3.4
conda activate test
python -c 'import cv2'
```

**Comment by RavinduDharmasena** [comment]
sure.. Executing your commands right now. Hang On

**Comment by nfahlgren** [comment]
Maybe you have OpenCV installed somewhere else on your system and it is conflicting with the conda environment? Do you get any output if you run `echo $PYTHONPATH`? If you do get one or more paths output from that command could you see if running this fixes the issue?

```bash
unset PYTHONPATH
python -c 'import cv2'
```

**Comment by RavinduDharmasena** [comment]
When `echo $PYTHONPATH` is executed it shows following result

`
:/home/ravindu/Documents/OpenDroneMap/SuperBuild/install/lib/python2.7/dist-packages
:/home/ravindu/Documents/OpenDroneMap/SuperBuild/src/opensfm`

This paths are required for functioning of OpenDroneMap and it is in the .bashrc. I will try out after commenting them out from .bashrc

**Comment by RavinduDharmasena** [comment]
@nfahlgren, I commented out the PYTHONPATH exports of OpenDroneMap (Actually they are their library paths) and executed the last 2 commands given by you. Now it doesn't show up any error in any conda environment. Is the OpenDroneMap is the problem here ?. How I can fix it ?. For my task I need the OpenDroneMap too.

**Comment by nfahlgren** [comment]
I think it is causing the issue. PYTHONPATH is being used by all conda environments even though it is pointing to a Python 2.7 package folder. Any package installed by OpenDroneMap in those paths that are also used by your conda environment(s) will cause a conflict. There are a couple solutions though.

## Option 1
PYTHONPATH is session specific, so you could have one terminal window/tab open using OpenDroneMap but in a separate window/tab you could be using conda without PYTHONPATH set. In a terminal where you want to use a conda environment you can do:

```bash
unset PYTHONPATH
conda activate research_dss
```

The unset command does not modify your Bash configuration files, it just removes the PYTHONPATH configuration for the current session. You would have to do this every time you start a new session where you will be using conda. It might be possible to have this happen automatically when you activate an environment but I'm not sure how to do that.

## Option 2
I'm not sure if this is possible but maybe OpenDroneMap could be uninstalled and reinstalled in a conda environment. If so, you would not need PYTHONPATH set anymore because the OpenDroneMap package and dependencies would be self-contained in a conda environment.

**Comment by RavinduDharmasena** [comment]
I think still they don't have OpenDroneMap as a library for conda environment. It is a command line toolkit. Thanks for the all of this stuff @nfahlgren.

**Comment by RavinduDharmasena** [comment]
Now I have another error. But I think it is better to open a new issue for that. So I'm closing this now.
