### ISSUE TITLE
TypeError: src2 is not a numerical tuple

### ISSUE THREAD

**Issue by RavinduDharmasena** [danforthcenter/plantcv#403]
I'm running the plantCV on a conda distribution and it is using python 3.7.3 and django 2.2.1. when I am running the python script included in the zip file it will throws the error given below.

`Traceback (most recent call last):
  File "testNIR.py", line 134, in <module>
    main()
  File "testNIR.py", line 77, in main
    comb_img = pcv.logical_or(e1_img, bkg_sub_thres_img)
  File "/home/ravindu/anaconda3/envs/research_dss/lib/python3.7/site-packages/plantcv/plantcv/logical_or.py", line 26, in logical_or
    merged = cv2.bitwise_or(bin_img1, bin_img2)
TypeError: src2 is not a numerical tuple`

Image and python script that I used in this scenario is given below.
[Test_NIR_1.zip](https://github.com/danforthcenter/plantcv/files/3315641/Test_NIR_1.zip)

Command I executed is `python testNIR.py -i ./IMG_8764_RGB.jpg -o ./output/nir_data.txt`

**Comment by nfahlgren** [comment]
Hi @RavinduDharmasena, looks like the issue is that on line 40 `pcv.threshold.custom_range` returns two images but you only have one variable, so that variable is a list of two images.

I think instead of

`bkg_sub_thres_img = pcv.threshold.custom_range(bkg_sub_img, [50], [190], 'gray')`

You want

`bkg_sub_thres_mask, bkg_sub_thres_img = pcv.threshold.custom_range(bkg_sub_img, [50], [190], 'gray')`

**Comment by RavinduDharmasena** [comment]
Now it shows a different error

`Warning: Invalid contour.
Traceback (most recent call last):
  File "testNIR.py", line 134, in <module>
    main()
  File "testNIR.py", line 117, in main
    if args.writeimg==True:
AttributeError: 'Namespace' object has no attribute 'writeimg'
`

**Comment by HaleySchuhl** [comment]
Looking at your script that you provided, it doesn't seem like you've added a `writeimg` argument in the setup of your options (lines 11-16). However, your script doesn't use `outfile` anywhere so I'd recommend removing lines 117-118 instead of adding an argument.

**Comment by RavinduDharmasena** [comment]
I commented out line 117 and 118 in the script and error is also became different. It is given below. There is a warning as well.

`Warning: Invalid contour.
/home/ravindu/anaconda3/envs/research_dss/lib/python3.7/site-packages/plantcv/plantcv/analyze_nir_intensity.py:60: RuntimeWarning: invalid value encountered in true_divide
  hist_percent = (hist_nir / float(pixels)) * 100
Traceback (most recent call last):
  File "testNIR.py", line 134, in <module>
    main()
  File "testNIR.py", line 121, in main
    nir_header, nir_data, nir_hist = pcv.analyze_nir_intensity(img, kept_mask, 256)
ValueError: not enough values to unpack (expected 3, got 0)`

**Comment by HaleySchuhl** [comment]
We have made some large changes to PlantCV in recent months. `pcv.analyze_nir_intensity()` used to return data and a histogram plot when `hist_plot=True`. Now it only returns the image. So depending on your PlantCV version you might need to update number of outputs you have in that line. The changes for each function across versions can be found [here](https://plantcv.readthedocs.io/en/latest/updating/).

Your error is actually traced back before the number of outputs though. I put your script into a Jupyter notebook and the warning message `Invalid contour` is getting output by line 112 `o, m = pcv.object_composition(rgb_img, roi_objects, hierarchy5)`. So the NIR function is throwing an error since it is trying to divide by zero since the mask you provide `kept_mask` is completely black. I'd suggest using Jupyter to look at the output of each step in your workflow. It seems like the script is very similar to our NIR tutorial but I don't think those steps are appropriate for the sample image you've provided. Most of the workflow steps in the NIR tutorial aim to segment out a single plant from the background. 

We have interactive tutorials [here](https://mybinder.org/v2/gh/danforthcenter/plantcv-binder.git/master?filepath=index.ipynb) so if you don't already have Jupyter you can upload your own image and run a preexisting tutorial to see what it looks like. Or you can input the steps from your script and run it on your image to see the intermediate debugging images.

**Comment by RavinduDharmasena** [comment]
@HaleySchuhl, Thank you pointing out the defects in the script. I think it is better to closed this issue as it looks like the issues are inside my custom created script.
