### ISSUE TITLE
setting dpi in print_image

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#406]
should matplotlib.rcParams be set in the numpy array type block as opposed to the block below or even at all?  this is in pcv.print_image().

i just happened to notice this when I opened up the function. at first glance it looks extraneous.

```
# Print numpy array type images
    image_type = type(img)
    if image_type == numpy.ndarray:
        matplotlib.rcParams['figure.dpi'] = params.dpi
        cv2.imwrite(filename, img)

    # Print matplotlib type images
    elif image_type == matplotlib.figure.Figure:
        img.savefig(filename, dpi=params.dpi)
```

**Comment by HaleySchuhl** [comment]
We wanted the user to be able to change DPI regardless of the image type that they are trying to save out. If a user doesn't change `pcv.params.dpi` then the line is extraneous since the matplotlib default is also 100 but a user can increase or decrease DPI and this parameter needs to be reset before the imaged gets printed out.

**Comment by dschneiderch** [comment]
@HaleySchuhl  cv2.imwrite uses matplotlib.rcParams?
