### ISSUE TITLE
Morphology workflow Mask issue 

### ISSUE THREAD

**Issue by rzarxwan** [danforthcenter/plantcv#415]
Working on PlantCV configuration is done and the test is working fine but when I go for original morphology workflow it gives an error. I am using plant cv in my Ubuntu machine the VIS workflow is running fine but in morphology workflow, I am having this error NameError: name 'mask' is not defined

I have tried to add a binary array it doesn't work.

# # Read in the previously created image mask 
# mask, path, filename = pcv.readimage("plant_mask.png")

# Crop the mask 
cropped_mask = mask[1150:1750, 900:1550]

Error NameError: name 'mask' is not defined 

I also this with uncommenting the 
# mask, path, filename = pcv.readimage("plant_mask.png") line but new error show up 

File "/media/Xyz/extra/plantcv/morphology/workflowname.py", line 44, in main
    skeleton = pcv.morphology.skeletonize(mask=cropped_mask)
  File "/media/Xyz/extra/anaconda3/lib/python3.7/site-packages/plantcv-3.4.1+10.g6922b4b-py3.7.egg/plantcv/plantcv/morphology/skeletonize.py", line 28, in skeletonize
    skeleton = skmorph.skeletonize(mask.astype(bool))
  File "/media/Xyz/extra/anaconda3/lib/python3.7/site-packages/skimage/morphology/_skeletonize.py", line 97, in skeletonize
    raise ValueError('Skeletonize requires a 2D array')
ValueError: Skeletonize requires a 2D array

**Comment by nfahlgren** [comment]
Hi @rzarxwan,

It looks like there is a syntax problem with our script at the bottom of the [morphology tutorial](https://plantcv.readthedocs.io/en/latest/morphology_tutorial/). The line that reads the mask image should be uncommented:

`mask, path, filename = pcv.readimage("plant_mask.png")`

For the second error you get, it looks like it is reading in your "plant_mask.png" file since you uncommented the `readimage` line but from the error I think your input image might not be a binary (grayscale) image. You could check the image type on the command-line in Ubuntu using:

```bash
file plant_mask.png
```

Or in Python you can check the dimensions:

```python
from plantcv import plantcv as pcv
import numpy as np
mask, path, filename = pcv.readimage("plant_mask.png")
np.shape(mask)
```

**Comment by HaleySchuhl** [comment]
Hi @rzarxwan ,

Please reopen this issue if you have any other issues with running an original morphology workflow! We can help you tweak your workflow if you upload an example image that you are using and the whole workflow.
