### ISSUE TITLE
Add hyperspectral image calibration function

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#442]
**Describe the solution you'd like**
Raw hyperspectral sensor exposure data needs to be calibrated to reflectances. The TERRA-REF team (https://github.com/terraref) has nice documentation on their calibration protocol (https://docs.google.com/document/d/1w_zHHlrPVKsy1mnW9wrVzAU2edVqZH8i1IZa5BZxVpo/edit#heading=h.jjfbhbos05cc).

**Describe alternatives you've considered**
We have been using essentially the same algorithm but this document formalizes it nicely.

**Comment by HaleySchuhl** [comment]
Proposed method:

![image](https://user-images.githubusercontent.com/44006936/68314693-372f1a80-007c-11ea-9a08-6a6cf35dd658.png)

Where S is the sample data,  D is the dark current data (in this case Headwall software already corrects for the dark current data) R the Reference data and RCλ,θ the correction value of the spectralon target provided with the target. I've got hyperspectral images for dark reference, white reference, and raw data; which get used where for calibration? 

I was looking at the calibration function on the branch that @Sanazjd was working on and it looks like that function is finding reflectance as follows:  `reflectance` = (`raw data` - `dark reference`) / (`white reference` - `dark reference`) but works by row rather than by hyperspectral wavelength bands (which shouldn't matter). 

I plan to start testing with raw, white reference, and dark reference image data and will write a function to calibrate hyperspectral data. However, we don't have the architecture setup to easily calibrate with PlantCV since users need to add arguments for multiple images to get used in a workflow.
