### ISSUE TITLE
tools to develop mask for naive bayes classifier

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#523]
Curious if you have a favorite tool for manually drawing a mask that can be used to the train the naive bayes classifier? Presumably the point of using the naive bayes classifier is that binary thresholding doesn't work well.

I can try the multiclass classifier with a csv of r,g,b values created from ImageJ too. Is there a way to record the pixel values of the pixels you click on with Pixel Inspector?

I think it would be a nice addition to the documentation if we had canonical methods for setting up these classifiers. happy to work on it but some guidance for existing practices would be helpful!

**Comment by nfahlgren** [comment]
We don't use the mask-based method very often anymore because like you said the naive Bayes method is most useful when typical thresholding doesn't work well. In our case we were making masks with typical PlantCV methods and then using those to train the classifier.

Because the classifier models the distribution of color properties, we only really need a statistically relevant sample size of the class/category colors, which I think makes the multiclass method trained with a color picker/pixel inspector tool ideal/faster.

For the latter, in ImageJ when you use the Pixel Inspector it opens a window with the RGB values for the central pixel plus all the neighbor pixels. You can select the neighborhood size. I think you can go as low as 1, which means you will get 9 pixels per click. When that box is open and in-focus you can use the keyboard copy shortcut (cmd-C or ctrl-C) to copy the RGB values. They are in a matrix array, but we need them in a column, so I paste the matrix into a text editor, let's say [Atom](https://atom.io/) for cross-platform compatibility. In Atom and other text editors you can do a find and replace with a regular expression, so I do:

Find: `\s+`
Replace: `\n`

That will replace all the spaces in the output matrix with line returns, then you can cut and paste the RGB values into a column in the training table. It's pretty quick if you keep the text editor setup for the find and replace, even if it is a bit awkward to use ImageJ + Atom + Spreadsheet to build the table.

**Comment by dschneiderch** [comment]
Got it. Thanks. fyi the[ table is tab-delimited](https://imagej.nih.gov/ij/plugins/pixel-tool/index.html) so Find works with \t.

**Comment by nfahlgren** [comment]
Ah okay!
