### ISSUE TITLE
Hyperspectral Calibration issue

### ISSUE THREAD

**Issue by codelearnstudio** [danforthcenter/plantcv#581]
Hi,  @HaleySchuhl & PCV Team,

**Hyperspectral Calibration issue**
I have Hyperspectral data collected from LemnaTec System. It contains the following items:
- raw datacube with hdr **datacube size:(454, 400, 940)**
- reference datacubes with metadata hdr files **datacube size: (1, 1600)**

I want to calibrate the raw datacube with 
**plantcv.hyperspectral.calibrate(raw_data, white_reference, dark_reference)**. while trying this with the following google drive shared data, I got an error as seen in to snapshot.
https://drive.google.com/file/d/1OL4rW31fszgSNEGziOfWdAftRP5f2Mt5/view?usp=sharing 

**To Reproduce**
- Installed Plantcv 3.8.0 using pip
1. run **test_calibration.py**
[test_calibration.zip](https://github.com/danforthcenter/plantcv/files/4723213/test_calibration.zip)

2. See error
![Screenshot from 2020-06-03 15-13-49](https://user-images.githubusercontent.com/64201651/83636314-5d417c80-a5c3-11ea-8341-1e69656199e9.png)

**Expected behavior**
- It should be returned with correct calibrated  datacube

**Local environment:**
 - OS: [Windows]
 - Environment[pip]
 - PlantCV Version [3.8.0]

**Comment by nfahlgren** [comment]
Hi @parthphoenix,

Thanks for providing all the data and scripts! 

The issue is that the white and dark references are 1600 px wide but your image is only 400 px wide. In the calibration formula we do the calculations in an array context so the dimensions have to line up. This is not necessarily valid but to test that this is the issue I truncated the white/dark arrays and calibration runs without error:

```python
dark.array_data = dark.array_data[:, 0:400, :]
white.array_data = white.array_data[:, 0:400, :]
```

**Comment by parthphoenix** [comment]
Hi @nfahlgren, 

Thanks for your suggestion.
I have applied for your suggestion[which is not necessarily valid]. But the Reflectance graph I was getting is not normalized and improper.
![reflectance](https://user-images.githubusercontent.com/64201651/83766092-94825d00-a699-11ea-9365-a336b4da1c9c.png)

So, We have replaced two for loops with bellow mentioned code snippet available in,
https://github.com/danforthcenter/plantcv/blob/62c5ccb4b762bc2566943e40b42e6972756899ce/plantcv/plantcv/hyperspectral/calibrate.py#L37-L45

```
output_calibrated = []
for i in range(0, raw_data.lines):
        raw_line = raw_data.array_data[i,].astype(np.float16)
        ans = raw_line - dark_reference.array_data
        ans1 = ans / den
        output_calibrated.append(ans1)
```
And we got a reflectance curve like,
![reflectance](https://user-images.githubusercontent.com/64201651/83767917-d0b6bd00-a69b-11ea-8d97-8ad6ee0be037.png)

Have you found this type of mapping issues earlier? If this is a common issue, then we need to understand this for a permanent solution since our LemnaTec System generating this Dark/White references.

**Comment by nfahlgren** [comment]
Hi @parthphoenix,

We have updated the calibration function in the default branch of PlantCV now. Thanks!

**Comment by parth-gb** [comment]
Thanks, @nfahlgren


> Hi @parthphoenix,
> 
> Thanks for providing all the data and scripts!
> 
> The issue is that the white and dark references are 1600 px wide but your image is only 400 px wide. In the calibration formula, we do the calculations in an array context so the dimensions have to line up. This is not necessarily valid but to test that this is the issue I truncated the white/dark arrays and calibration runs without error:
> 
> ```python
> dark.array_data = dark.array_data[:, 0:400, :]
> white.array_data = white.array_data[:, 0:400, :]
> ```

As you suggested for the first 400 data, Instead, we have taken every 4th data and the results are as expected. The graph is looking nearly similar to the ideal one. I know that's not valid but results seem to be expected.

**Comment by parthphoenix** [comment]
> Hi @parthphoenix,
> 
> Thanks for providing all the data and scripts! 
> 
> The issue is that the white and dark references are 1600 px wide but your image is only 400 px wide. In the calibration formula we do the calculations in an array context so the dimensions have to line up. This is not necessarily valid but to test that this is the issue I truncated the white/dark arrays and calibration runs without error:
> 
> ```python
> dark.array_data = dark.array_data[:, 0:400, :]
> white.array_data = white.array_data[:, 0:400, :]
> ```

Hi @nfahlgren,

Thanks.

As you suggested for the first 400 data, instead we have taken every 4th data and the results areas expected. The graph is looking nearly similar to the ideal one. I know that's not valid but results seem to be close.
