### ISSUE TITLE
Ellipse ROI causing an error

### ISSUE THREAD

**Issue by aaronshalev** [danforthcenter/plantcv#589]
Hi there,

Upon using plantcv.roi.ellipse(), I get the error that  "ellipse() takes at most 5 arguments (8 given) which is directed at line 173 of roi_methods.py. This seems to be happening because OpenCV has an 8 parameter cv2.ellipse(), as well as one with only 5 parameters. The 5 parameter cv2.ellipse() takes as input a box which will inscribe an ellipse, while the 8 parameter cv2.ellipse() instead takes as input several dimensions of the ellipse itself. We would benefit from the 8 parameter verison, though, because plantcv.analyze_object() returns the dimensions of the ellipse rather than the box.

Attached below is the .py file and image I used which encountered this error. I have restated what I am trying to do in the comments of this script. 

Without an error occurring, I would expect plantcv.roi.ellipse() to return an roi countour and hierarchy in the same way the plantcv.roi.rectangle() works, as well as an image with the ellipse on top. I did use the rectangular ROI without a hitch on line 34 of my file.

Local environment:
 - OS: Windows
 - Environment: conda
 - PlantCV Version: 3.8.0

I expect this bug has something to do with the version of OpenCV. I have version 3.4.1. It is very possible I am missing something quite obvious here... if so, I apologize in advance!

Thank you for your time,

Aaron Shalev

File:
[elliptical_roi.zip](https://github.com/danforthcenter/plantcv/files/4815687/elliptical_roi.zip)

Image:
[plant_img.zip](https://github.com/danforthcenter/plantcv/files/4815708/plant_img.zip)

**Comment by nfahlgren** [comment]
Hi @aaronshalev, thanks for reaching out! I appreciate that you sent the code and sample image, really helpful!

There are two things going on. The error message you get from OpenCV is actually misleading. As you found, there are two versions of `cv2.ellipse` and the error suggests we are using the one that takes a rotated rectangle, but we are using the 8-parameter version. In testing I found that the issue was that the observations are float values and the ellipse drawing function only takes integers. By wrapping `int()` around each of the observations passed to `plantcv.roi.ellipse` it was able to draw the ellipse. Unfortunately, the error was not clear at all that that's what was going on!

However, when I looked at the resulting ellipse it did not look correct. I went back through the OpenCV documentation on bounding ellipses and realized that we are not using the measurements correctly in `plantcv.analyze_object`.  When we run `cv2.fitEllipse` we treated the output as `((x, y), (major, minor), angle)` but the output is actually a rotated rectangle rather than the ellipse directly, so it's actually `((x, y), (h, w), angle)`. 

We'll work on updating `plantcv.analyze_object` to correctly output the measurements we thought we were measuring and so that they are compatible with `plantcv.roi.ellipse`.

**Comment by aaronshalev** [comment]
Thank you for the quick reply!

Changing the float values to integers seems to have resolved the error that occurred before. Unfortunately, the ellipse extends outside of the image, so I can't use it, but this is a separate problem for another day. :)

As an alternative to defining an ROI around the plant using the ellipse measurements from plantcv.analyze_object, perhaps it is instead easier to define the ROI using the vertices from the convex hull using the PlantCV custom ROI feature. I see that plantcv.analyze_object returns how many vertices the convex hull has, but not the coordinates. I will look into this.

Thank you again for the help!

**Comment by nfahlgren** [comment]
Hi @aaronshalev,

I was wrong, although the `cv2.fitEllipse` function does return the measurements we need to draw an ellipse. The issue I missed is that we record the major and minor access lengths but the `cv2.ellipse` function and the `plantcv.roi.ellipse` function take the radius of each instead. There is a documentation issue though. We specify that r1 = major axis and r2 = minor axis but these should be reversed. This means in your script the following returns the correct ellipse:

```python
roi, roi_hierarchy= pcv.roi.ellipse(masked,
                                    x=int(pcv.outputs.observations['ellipse_center']['value'][0]),
                                    y=int(pcv.outputs.observations['ellipse_center']['value'][1]),
                                    r1=int(pcv.outputs.observations['ellipse_minor_axis']['value'] / 2),
                                    r2=int(pcv.outputs.observations['ellipse_major_axis']['value'] / 2),
                                    angle=int(pcv.outputs.observations['ellipse_angle']['value']))
```

To verify this, we can look directly at the OpenCV results:

```python
plant, plant_mask = pcv.object_composition(img=img, contours=plant_objects, hierarchy = plant_hierarchy)
analysis_image = pcv.analyze_object(img=img, obj=plant, mask=plant_mask)
ellipse = cv2.fitEllipse(plant)
cp = np.copy(analysis_image)
cp = cv2.ellipse(cp, min_ellipse, (0, 255, 255), 2)
pcv.plot_image(cp)
```

**Comment by aaronshalev** [comment]
Hi @nfahlgren,

This has resolved the issue! Many thanks for the time you put into trouble shooting this issue.
