### ISSUE TITLE
Morphology - "Unable to combine stem objects"

### ISSUE THREAD

**Issue by laurakleinLW** [danforthcenter/plantcv#599]
**Describe the bug**
I am working through the morphology workflow on one of my images in jupyter notebook and keep getting the error message "Unable to combine stem objects" when running `pcv.morphology.segment_insertion_angle`. I would love help with: 
1. Why am I receiving the error message "Unable to combine stem objects"? 
2. Looking at the source code, I see the error is related to making sure the stem objects are a single contour via a loop count. When I look at the debugged skeleton image, there is a break in the skeleton of the image. Can you confirm this error message related to breaks in the skeleton? If yes, I suspect it has something to do with the thresholding and masking steps, but I'm not sure.
3. If this error is related to the broken skeleton, why does the workflow work until the `pcv.morphology.segment_insertion_angle` step?

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Starting with image '...'
2. Run function(s) '....'
3. See error

```
from plantcv import plantcv as pcv
print(pcv.__version__)
# alternatively pip show plantcv
print(pcv.__file__)

class options:
    def __init__(self):
        self.image = "./mask_crop2.png"
        self.debug = "plot"
        self.writeimg= False 
        self.result = "./skeleton_tables/"
        self.outdir = "."

args = options()

pcv.params.debug = args.debug

img, path, filename = pcv.readimage(filename=args.image)

reductions = [.1, .2]
sizes = [10, 20, 30, 40, 50, 60]

for reduction in reductions:
       temp_cropped_mask = pcv.resize(img, reduction,reduction)
       temp_skeleton = pcv.morphology.skeletonize(mask=temp_cropped_mask)
        for size in sizes:
               print("Reduction: ", reduction, ",","Size: ",size)
               img1, seg_img, edge_objects = pcv.morphology.prune(skel_img=temp_skeleton, size=size, mask=temp_cropped_mask)
        
        # Identify branch points (fuchsia pts)  
        branch_pts_mask = pcv.morphology.find_branch_pts(skel_img=temp_skeleton, mask=temp_cropped_mask)
        
        # Identify tip points (green pts)   
        tip_pts_mask = pcv.morphology.find_tips(skel_img=temp_skeleton, mask=None)
        
        # Sort segments into primary (stem; fuchsia) objects and secondary (leaf; green) objects. 
        leaf_obj, stem_obj = pcv.morphology.segment_sort(skel_img=temp_skeleton, objects=edge_objects, mask=temp_cropped_mask)
        
        # Identify segments (rainbow; assumes leaves are objects of interest - aka objects=leaf_obj)
        ## Because leaves are not truly leaves here, I am interested in 'objects=stem_obj' instead - I assume this will measure the internodes
        pcv.params.text_size=.5 
        pcv.params.text_thickness=2
        segmented_img, labeled_img = pcv.morphology.segment_id(skel_img=temp_skeleton, objects=stem_obj, mask=temp_cropped_mask)
        
        # Measure path lengths of segments     
        labeled_img = pcv.morphology.segment_path_length(segmented_img=segmented_img, objects=stem_obj) 
        
        # Find leaf angles      
        labeled_img = pcv.morphology.segment_angle(segmented_img=segmented_img, objects=leaf_obj)
        
        # Measure the leaf insertion angles      
        labeled_img = pcv.morphology.segment_insertion_angle(skel_img=temp_skeleton, segmented_img=segmented_img, leaf_objects=leaf_obj, stem_objects=stem_obj, size=20)                                                       
                                                               
        #print results
        result_filename = args.result + filename[:-4] + "_" + str(reduction) + "_" + str(size) + ".txt"
        #print(result_filename)
        pcv.print_results(filename=result_filename)
        pcv.outputs.clear()
```

**Expected behavior**
I expected the skeleton to be complete and the workflow run relatively smoothly.

**Local environment (please complete the following information):**
 - OS: macOS Catalina v10.15.6
 - Environment: conda
 - PlantCV Version [e.g. 3.8.0]

**Additional context**
Looking at the debugged skeleton plot, I can see there is a break in the skeleton. My image is pretty large (1426 × 6518 pixels), so I'm experimented with reducing the image dimensions ("reductions" loop) and changing the `size` parameter during the pruning phase ("sizes" loop). A 90% reduction works better than an 80% reduction, but the debugged skeleton still has breaks. I have also experimented with cropping the image, but still find breaks in the skeleton that I don't understand why they form. Attached is the image I used. Thank you!
![mask_crop2](https://user-images.githubusercontent.com/67664926/88351745-2c9cda00-cd0c-11ea-834b-743796d2eae5.png)

**Comment by HaleySchuhl** [comment]
Hi @laurakleinLW ,

Thanks for reaching out! I was able to replicate your error in my local PlantCV environment (v3.9 on mac). 

The complexity of mask and creating the skeleton at fuller resolutions is causing a lot of barbs and extra segments to show up. The sorting algorithm is getting confused when there are detached objects, like the salt noise in your mask, since they get sorted as stem, but aren't connected to the rest of the stem. This doesn't get triggered at the more aggressive reduction size because those noisy pixels are sampled down. The solution I see is cleaning the original mask a little more (probably useful here would be [pcv.fill](https://plantcv.readthedocs.io/en/latest/fill/#fill) [pcv.fill_holes](https://plantcv.readthedocs.io/en/latest/fill_holes/) and using erode and dilate steps can also help to smooth rough edges of binary masks). Any pepper noise within the mask will show up in skeletons as closed loops which break underlying sorting algorithms in the morphology subpackage so filling in those holes and the detached salt noise should help a lot. Otherwise, I think the debug images for reduction=0.1 look pretty successful! Resizing is down sampling a lot of the problematic pixels that cause issues downstream. Let me know if this helps and any other questions that come up!

**Comment by laurakleinLW** [comment]
Thanks for your help, @HaleySchuhl ! I figured it was something to do with the masking. I will troubleshoot this part of the process.
