### ISSUE TITLE
bioconda update to 3.9 missing

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#604]
the bioconda distribution hasn't been updated to 3.9. seemed slow so I thought i'd bring it to your attention.

**Comment by nfahlgren** [comment]
Yeah, I think something is wrong with the build system: https://github.com/bioconda/bioconda-recipes/pull/23305. I opened an issue and tagged the team but haven't heard back yet. I'm not 100% sure what's going on but we didn't change anything significant on our end. Within the build environment it can't import OpenCV because it can't find the libGL linked library. That's been an issue in the past that went away but now it's back again.
