### ISSUE TITLE
Incorporating date/time processing in the json config file for workflow parallelization

### ISSUE THREAD

**Issue by VictorNeaco** [danforthcenter/plantcv#644]
I have a working workflow parallelization setup to batch process a folder of images, but I was wondering if the "start date" parameter in the JSON config file can accept date/time JSON functions like **$now()** so that it will automatically select the latest images that were taken on the day of and not any previous images that may also be in the same folder. 

Thanks!

**Comment by HaleySchuhl** [comment]
I don't believe our ability to filter on timestamps extends to any date/time JSON functions, such as `$now()`. It's my understanding that we only check whether image date-time fall outside or inside the included range, but @nfahlgren can correct me here if I'm mistaken!

**Comment by dschneiderch** [comment]
I'm having trouble understanding what you are expecting. if the startdate is now() then you'll never get any images. If you want the latest images, you need to decide how far back in to the past you want to process images.   You could for example set the start date to be 1 hour behind now.  if you leave end date blank it is automatically now() so you'd only get images within the last hour of running the workflow.

if you want to automate a moving start date that is up to 1 hour ago, then you could use a simple python script that recreates the workflow config using the python interface with a new start date. in python you can access now() through the datetime package.

```
import datetime
datetime.datetime.now()
```

Another option to create a realtime processing setup is to use a Makefile or Snakemake to only process files with modifications dates newer than some other file. you could create a small log file everytime you run the workflow to keep track of the timestamps. In that case you'd accept the defaults for startdate and enddate in the config file because only new images would be used in the workflow to begin with.

**Comment by nfahlgren** [comment]
I was just writing this as @dschneiderch responded :)

It's a cool idea but it doesn't work as far as I can tell. I don't think the Python `json` package parser evaluates Javascript functions embedded in JSON.

But what you are trying to do makes a lot of sense and could be done with a small Python program that runs `plantcv-workflow.py` but sets the start date based on your requirements:

```python
#!/usr/bin/env python

import argparse
import datetime
from subprocess import call
from plantcv.parallel import WorkflowConfig


def options():
    """Parse command-line arguments."""
    desc = "Run daily PlantCV workflow."
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument("--config", help="PlantCV workflow config file.")
    args = parser.parse_args()

    return args


def main():
    # Parse command-line arguments
    args = options()

    # Get today's date
    today = datetime.date.today()

    # Create PlantCV WorkflowConfig instance
    config = WorkflowConfig()

    # Import saved configuration file
    config.import_config(config_file=args.config)

    # Configure start date
    config.start_date = today.strftime('%Y-%m-%d')

    # Save configuration file
    config.save_config(config_file=args.config)

    # Run plantcv-workflow.py
    call(["plantcv-workflow.py", "--config", args.config])


if __name__ == "__main__":
    main()

```

**Comment by dschneiderch** [comment]
@nfahlgren don't you need to set the timestampformat to %Y-%m-%d for the date filtering to work?
https://github.com/danforthcenter/plantcv/blob/7308f1795c5c46d3cb17a5eb7fd96f21f9c7b974/plantcv/parallel/parsers.py#L30

**Comment by nfahlgren** [comment]
@dschneiderch yep, you're right. I edited the script in the comment above.

**Comment by dschneiderch** [comment]
a small caveat, the timestamp in the image filename needs to match that of timestampformat.

**Comment by nfahlgren** [comment]
Yeah, the strftime string `%Y-%m-%d` would need to be adjusted to match the data. And another potential augmentation would be the date itself. I put it as today but depending on how data is collected and when this script would be scheduled to run you could subtract a day from the current day:

```python
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
config.start_date = yesterday.strftime('%Y-%m-%d')
config.end_date = today.strftime('%Y-%m-%d')
```

This way all data collected the previous day would be analyzed up to the current day.

**Comment by VictorNeaco** [comment]
This was super helpful! 
Thank you for the information.

**Comment by HaleySchuhl** [comment]
Feel free to reopen this issue with further comments or questions!!
