### ISSUE TITLE
error with interactive image visualization

### ISSUE THREAD

**Issue by EdwinP503** [danforthcenter/plantcv#647]
Hi I am new with PLantCV and after installing using Conda, I tried to change to an interactive plot as you did in the workshop for PhenomeForce. While using %matplotlib notebook, I get the following error "Javascript Error: Can't find variable: IPython" 

I am using Python 3.8.3 and PLantCV 3.10.1 on a Mac platform.

-Edwin Polanco

**Comment by nfahlgren** [comment]
Hi Edmin, thanks for reaching out! I am not 100% sure this will fix the issue, but a quick thing to try is to activate your PlantCV environment on the command line and install the nb_conda package:

```bash
conda activate plantcv
conda install nb_conda
```

But if that does not help definitely let us know!

**Comment by EdwinP503** [comment]
Hi,

So I followed instructions and I actually saw "notebook" being downloaded. However, now I have an issue because when I run `jupyter-lab `after I use `conda activate plantcv ` I am unable to `import matplotlib` it says the `ModuleNotFoundError`. 

But I kind of see where the issue is, I installed PlantCV on my Home directory (the packages may not be in the same place). Is there a way I can clean my computer from all the files downloaded for PlantCV and download them again correctly?

**Comment by nfahlgren** [comment]
Oh I have run into this issue before. Jupyterlab does not support the `notebook` interactive method, I think it has been replaced with `widget` instead. I have gotten it working before but it is trickier to set up. I just tested this protocol and got it working in my environment (assuming jupyterlab is already installed, otherwise it would be added to the conda install command):

```bash
conda activate plantcv
conda install nodejs ipympl
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
jupyter nbextension enable --py widgetsnbextension
```

**Comment by nfahlgren** [comment]
Or an alternative is to run `jupyter notebook` instead of `jupyter-lab`, it just uses the older Jupyter interface.

One other thing that I am not 100% sure about that may need to be done is running `conda install nb_conda` in your base environment. I cannot remember whether that is needed or not to make your individual conda environments visible in Jupyter. I need to set everything up on a clean system again to update our docs on what is required these days.

**Comment by EdwinP503** [comment]
Thank you so much! Indeed it does work when using `jupyter notebook` instead of `jupyter-lab`, but I did ran `conda install nb_conda` on my base environment so I am not sure if that contributed to it.

**Comment by nfahlgren** [comment]
Great, thanks @EdwinP503! I will close this for now but definitely let us know if you have any other questions!
