### ISSUE TITLE
How do i read multiple images in Plantcv?

### ISSUE THREAD

**Issue by bharathreddy1997** [danforthcenter/plantcv#651]

**Comment by HaleySchuhl** [comment]
Hi @bharathreddy1997 ,

Thanks for opening an issue! If you have two or more image files that you want to use in a PlantCV workflow (one example we have in documentation is using a background image for background subtraction), you can just use the `pcv.readimage` function as many times as needed. Are your analysis goals to run a PlantCV workflow over an entire dataset or to analyze groups of images separately? What type of pipeline are you working on?

**Comment by bharathreddy1997** [comment]
Hi, @HaleySchuhl  I want to run Plantcv on my image dataset which consists of 300 images.  I want to detect the type of plant-based on its leaf structure.

**Comment by HaleySchuhl** [comment]
Awesome! The [VIS tutorial](https://plantcv.readthedocs.io/en/latest/vis_tutorial/) would probably be most similar since we analyzed RGB images for shape with `pcv.analyze_object`. Once you have a workflow that works well on a representative subset of your 300 image dataset, then you can execute the workflow in parallel over an entire directory, and PlantCV-workflow will compile all extracted data into a text file. Please don't hesitate with further questions that come up regarding [workflow parallelization](https://plantcv.readthedocs.io/en/latest/pipeline_parallel/)!.
