### ISSUE TITLE
Analysis of thermal image of leaf for diseases. Check if red or yellow color is present in thermal image.

### ISSUE THREAD

**Issue by anshikasharma26** [danforthcenter/plantcv#653]
According PlantCV's code for "analyze color" not much information can be extracted from the histogram created. 
Is there any other workflow or function that could be of help for the problem stated?

**Comment by nfahlgren** [comment]
Hi @anshikasharma26, when I want to analyze the color of something I typically use the hue data output by `anayze_color`.  Hue is a measure of the "pure" color of a pixel, measured as an angle around a color wheel. 

How you analyze the data really depends on the question and distribution of the data. If your data (the hue frequency distribution) are normal, univariate distributions then one of the summary statistics we output for hue (mean or median) could suffice to compare between samples. In these workshop materials, we have some R code for plotting the hue frequency data: https://github.com/danforthcenter/phenome2020-workshop/blob/master/session1-image-analysis/analyze_infection_by_hue.ipynb.

If instead, you have a mixture of distributions you could use a Gaussian Mixture Model to calculate the mean of each component. This code is from an older version of PlantCV, but we used a GMM here: https://github.com/carringtonlab/tcv-image-analysis/blob/master/plantcv-arabidopsis-tcv-image.py.

If the distribution is more complex, another approach to address your goal might be to define ranges of hue values as buckets. So you could take the output hue frequencies and summarize them more by dividing the hue angles (https://en.wikipedia.org/wiki/HSL_and_HSV#/media/File:HSV-RGB-comparison.svg) into ranges you define: e.g. red = 0 degrees +/- 20 degrees, yellow = 60 degrees +/- 20 degrees, etc.

But one other suggestion that might apply. FLIR cameras output a pseudocolored RGB image that sounds like what you have. But in that image is embedded the raw data in temperatures. My understanding is that FLIR software can export the raw data as CSV and our `readimage` function can import the temperature values from this CSV file. Then instead of using `analyze_color` you could use `analyze_thermal_values`. It would output a frequency distribution of temperatures instead of colors, so the same analyses above could apply but might potentially be more intuitive because the units would be directly related to what you are measuring.
