### ISSUE TITLE
Please forgive my lack of experience, I need some guidance

### ISSUE THREAD

**Issue by Lokissonne** [danforthcenter/plantcv#66]
I am trying to run the example VIS pipeline and I am receiving this error and do not know what I am doing wrong. 
Using Ubuntu 16.04
Using the same original img from the VIS example named plant.jpg
 
files are stored in /media/Hydro_Photo/Storage/plantcv

Is it naive of me to attempt Plant CV without experience in Open CV?!?

./plantana.py -i testimg.png -o ./output-images -D

This does not seem to work at all^^^

python2.7 plantana.py -i plant.jpg -o /output-images -D

This command returns

WARNING: Make sure ROI is COMPLETELY in frame or object detection will not perform properly
Warning: Invalid contour.
Traceback (most recent call last):
  File "plantana.py", line 92, in <module>
    main()
  File "plantana.py", line 78, in main
    device, shape_header, shape_data, shape_img = pcv.analyze_object(img, args.image, obj, mask, device, args.debug, args.outdir + '/' + filename)
  File "build/bdist.linux-x86_64/egg/plantcv/analyze_object.py", line 39, in analyze_object
TypeError: object of type 'NoneType' has no len()

Plantana.py line 78 and 92
#78

 device, shape_header, shape_data, shape_img = pcv.analyze_object(img, args.image, obj, mask, device, args.debug, args.outdir + '/' + filename)

*#92*

ierarchy3, kept_mask, obj_area = pcv.roi_objects(img, 'partial', roi1, roi_hierarchy, id_objects, obj_hierarchy, device, args.debug)

Can anyone spare some time to help a young budding Environmental Roboticist out?
Things to check?

**Comment by jshoyer** [comment]
Hi Lokissonne,      The vis tutorial needs some updates, as noted under issue #30.
I'm not sure what your plantana script is (we should really make the pipeline illustrated in that tutorial downloadable as a plain text file...). Is your script executable? If not, try `chmod +x plantana.py`.
You might try running your script without the `-o` flag to start. The output directory must exist beforehand, and the debug output shows up in your current working directory either way....

If none of the above helps, you might want to try a simpler pipeline script. I'd guess that `shape_img` is not being created correctly, perhaps because the input image is not being read in correctly at all. Are the debug images 0, 1, 2... being created?

**Comment by maliagehan** [comment]
Hi Lokissonne, do you still need assistance or has your issue been resolved?

**Comment by Lokissonne** [comment]
Thank you for your responses. I have not had much time to sit down for a couple of hours and go for round two. I will try a few things as suggested and try to put together a more concise list of problems/errors I am running into if any. Thank you so much for your time.

**Comment by maliagehan** [comment]
great just let us know!

**Comment by Lokissonne** [comment]
Well I have got everything up and running. Thank you so much for the help.

**Comment by maliagehan** [comment]
great! Good luck with the analysis.
