### ISSUE TITLE
Please support the newest version of opencv

### ISSUE THREAD

**Issue by JimXu1989** [danforthcenter/plantcv#667]
Thanks a lot for your sharing !!! Great work!!!

while when I install plantcv, it install old version of opencv by default, I want use the newest version of opencv, 4.5.1, what should I do?

**Comment by nfahlgren** [comment]
Hi @JimXu1989, apologies for the delay! Our plan is to migrate to OpenCV when we start the PlantCV v4 series in the next few months. I tested it out on the current version 3.10.1 and it almost works, but we need to update line 302 in `plantcv/plantcv/roi/roi_methods.py` to make it OpenCV version agnostic. That line currently expects 3 outputs, but in OpenCV4 there are only 2. We only care about those two anyhow, so that will be an easy fix that we can do now. Once that's done you should be able to use OpenCV4 even though it wouldn't officially be in our requirements file yet

**Comment by JimXu1989** [comment]
> Hi @JimXu1989, apologies for the delay! Our plan is to migrate to OpenCV when we start the PlantCV v4 series in the next few months. I tested it out on the current version 3.10.1 and it almost works, but we need to update line 302 in `plantcv/plantcv/roi/roi_methods.py` to make it OpenCV version agnostic. That line currently expects 3 outputs, but in OpenCV4 there are only 2. We only care about those two anyhow, so that will be an easy fix that we can do now. Once that's done you should be able to use OpenCV4 even though it wouldn't officially be in our requirements file yet

plantcv's fill region method really better then opencv's crossponding method !!
