### ISSUE TITLE
Output skeleton as SVG

### ISSUE THREAD

**Issue by spleeen1** [danforthcenter/plantcv#674]
Hi, Thank you so much for creating plantcv! I love it! 
this is really not an issue only a question: I'm new to python and searching for a way to output the skeletonized binary data to a contour that I can output as SVG with something like: "contours, hierarchy = cv2.findContours(edge, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)". Do you think this is possible? 
Best, Simon

**Comment by HaleySchuhl** [comment]
Hi @spleeen1 ,

Thanks so much for reaching out! That should be totally doable. We use the OpenCV contour/hierarchy data structure throughout PlantCV, so the code you provided should work well! The PlantCV function `pcv.find_objects` is actually a wrapper of `cv2. findContours`, so that could be another method to obtain the contours of a skeleton such that you can save them out. Let us know how it goes!

**Comment by spleeen1** [comment]
thx so much for taking the time to answer! I tried following: 
skeleton = pcv.morphology.skeletonize(mask=thresh2)
edge_objects = pcv.morphology.prune(skel_img=skeleton, size=10)
contours, hierarchy = pcv.find_objects(edge_objects, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

but I'm getting an error that says: "TypeError: find_objects() takes 2 positional arguments but 3 were given" 

I think I don't really understand how I can convert the skeleton into vectors..

Thanks for your help!

**Comment by HaleySchuhl** [comment]
The `pcv.find_objects` [function]( ) takes an image and a binary mask as input. The `prune` function is also outputting 3 objects: `pruned_img`, `segmented_img`, `segment_objects`, so with including that step you will already have a list of contours within the `segment_objects` output. There still might be good reason to utilize `pcv.find_objects` before saving out the contours if you'd like the skeleton combined into a single contour (rather than a list of the contours for each segment that makes up the skeleton).

**Comment by spleeen1** [comment]
okay thank you! 
I have to admit I am little bit lost here. I try to isolate where the skeleton vectors are but I don't find in the morphology sub-package. Could you maybe provide me with a line of code on how to convert the skeleton binary into a structure that is readable by "contours,hierarchy = cv2.findContours(skeleton, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)" ?

**Comment by HaleySchuhl** [comment]
Sure! Sorry for the confusion. I think something like this will achieve what you're after:

```
import numpy as np
import plantcv from plantcv as pcv
... 
skeleton = pcv.morphology.skeletonize(mask=thresh2)
pruned_img, segmented_img, segment_objects = pcv.morphology.prune(skel_img=skeleton, size=10)
cnts, hrchy = pcv.find_objects(img=pruned_img, mask=pruned_img)
contours, skel_mask = pcv.object_composition(img=segmented_img, contours=cnts, hierarchy=hrchy)
np.savez("skeleton_contours", contours) # this will save the contours out as a .npz file (not sure how to do SVG) 

```

Another option would be the following: 
```
skeleton = pcv.morphology.skeletonize(mask=thresh2)
pruned_img, segmented_img, segment_objects = pcv.morphology.prune(skel_img=skeleton, size=10)
contours, hierarchy = cv2.findContours(pruned_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

```

**Comment by spleeen1** [comment]
Dear Haley, 
Thanks so much, it's working now! 
It was **almost working** out of the box but for some reason I had to change 
`contours, hierarchy = cv2.findContours(pruned_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)`
into:
`contours, hierarchy = cv2.findContours(pruned_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)[-2:]`

now it works!!
(For anyone running into this problem: I am running several conda environments, with opencv 3.4.2 and everywhere the above mentioned line works. also after downgrading my plantcv environment to use opencv 3.4.2. no luck. )

**Comment by HaleySchuhl** [comment]
@spleeen1 Awesome! Thanks for providing that update. We're dealing with the same thing across a few PlantCV functions between OpenCV various versions, especially as we look to adding OpenCV 4 support haha. I'm going to close this issue for now, but feel free to reopen with any further questions/comments/suggestions 😃
