### ISSUE TITLE
Problem with conversion from json to csv

### ISSUE THREAD

**Issue by RosarioIacono** [danforthcenter/plantcv#688]
Hello,
I am trying the VIS workflow with the standard image provided in your tutorial (https://plantcv.readthedocs.io/en/stable/vis_tutorial/ ).

My results are stored as:
`self.result = "./vis_tutorial_results.json`

When  I try to convert the file from json to csv using the line:
`plantcv-utils.py json2csv -j vis_tutorial_results.json -c CSV`

The following error is thrown:
![Screenshot from 2021-02-20 10-13-13](https://user-images.githubusercontent.com/45822340/108590533-541c5980-7364-11eb-879e-8e2d01cae9ea.png)

Am I doing something wrong?

**Comment by nfahlgren** [comment]
Hi @RosarioIacono,

Thanks for pointing this out to us. I looked at the documentation and what we have about converting to CSV is not quite correct. When the workflow is run through the end and you create `vis_tutorial_results.json`, this JSON file cannot be directly converted to CSV using `plantcv-utils.py json2csv` (currently at least). The `json2csv` converter was built to convert the aggregate JSON file created when running `plantcv-workflow.py` into CSV. `plantcv-workflow.py` runs the workflow script in parallel on an image dataset, and the results files like `vis_tutorial_results.json` are created as intermediates. Part of the PlantCV parallel package aggregates the individual results JSON files into the final output JSON file. That is probably not super clear, especially because both the results files and the final output file are both JSON. 

I think we should have the functionality to output these intermediate results into CSV format, and I outlined a strategy for adding a new method for this in #689. In the meantime, I'm marking this as a bug in the documentation at least.

Thanks!

**Comment by RosarioIacono** [comment]
Hello @nfahlgren, thanks for your prompt reply. Yesterday I managed the conversion easily using rjson package in R. In three steps the json file is first converted to a list of dataframes and then joined together with rbind. I think could be a perfect alternative for people who want to take to the downstream analysis only the intermediate files. My final goal is to analyse several plants in parallel, so I should not have problem in the final analysis.

Thank you very much for the support.

**Comment by nfahlgren** [comment]
Hi @RosarioIacono, just wanted to let you know that in #731 we added a method for saving outputs directly to CSV using `pcv.outputs.save_results(filename, outformat="csv")`. The save_results method replaces the `pcv.print_results` method, though print_results will continue to work until it's removed at a later date.
