### ISSUE TITLE
dockerhub image not updated

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#695]
**Describe the bug**
i did a fresh pull of danforthcenter/plantcv from dockerhub but am getting a dirty plantcv 3.10.1 rather than 3.11.1

is something blocked from updating?

```
ubuntu@primary:~$ docker images
REPOSITORY    TAG       IMAGE ID       CREATED         SIZE
hello-world   latest    bf756fb1ae65   13 months ago   13.3kB
ubuntu@primary:~$ docker pull danforthcenter/plantcv
Using default tag: latest
latest: Pulling from danforthcenter/plantcv
83ee3a23efb7: Pull complete
db98fc6f11f0: Pull complete
f611acd52c6c: Pull complete
724e03a65ce0: Pull complete
513e138b0e94: Pull complete
48f0bd4aefb5: Pull complete
4f4fb700ef54: Pull complete
b4de871b77c8: Pull complete
0b03df09b2e6: Pull complete
fa78867bfcd3: Pull complete
47cf22ed95c5: Pull complete
9ecce3ab59b4: Pull complete
5ec66779f1e5: Pull complete
cd7851ccfb49: Pull complete
e80214e887dd: Pull complete
b96af1630e18: Pull complete
bec9edeb94f8: Pull complete
dbb61cd8d6ce: Pull complete
acdef2af109f: Pull complete
79fe7147099c: Pull complete
d0d150a35f2c: Pull complete
5e1502d3b9e6: Pull complete
d9a2af0087e9: Pull complete
Digest: sha256:5d8f6103c7121b81f005cf6050b42808474ba879f08d8211078f9e0ae37a8cc9
Status: Downloaded newer image for danforthcenter/plantcv:latest
docker.io/danforthcenter/plantcv:latest

ubuntu@primary:~$ docker run danforthcenter/plantcv start.sh ipython from plantcv import plantcv as pcv; pcv.__version__
Executing the command: ipython from plantcv import plantcv as pcv
[TerminalIPythonApp] WARNING | File 'from' doesn't exist
pcv.__version__: command not found
ubuntu@primary:~$ docker run danforthcenter/plantcv start.sh ipython -c 'from plantcv import plantcv as pcv; pcv.__version__'
Executing the command: ipython -c from plantcv import plantcv as pcv; pcv.__version__
Out[1]: '3.10.1+244.g794af426.dirty'
```

**Comment by nfahlgren** [comment]
Hmm, I'm not sure what happened. There are no errors but it does look like no new container was built for PlantCV v3.11 when the release was made: https://hub.docker.com/repository/docker/danforthcenter/plantcv/builds.

There is one now because I merged a pull request today.

I had trouble with the GitHub Actions workflow for deploying PlantCV on a new release, so maybe that also prevented it from triggering a new Docker build.

**Comment by dschneiderch** [comment]
Where can you see the history of builds?  Or is that only for you as owner?
I pulled again and now its
Out[1]: '3.11.0+3.gd86fe6b4.dirty'
Rather than 3.11.1.

Also, doesn’t dirty mean there are uncommitted changes, which doesn’t make much sense in this context…?

**Comment by nfahlgren** [comment]
Looks like I can only access the builds link I sent above when logged into Docker Hub...not sure why it's secret.

The version shows up as "dirty" because we modify the `requirements.txt` file when building the Docker container, prior to installing PlantCV. Maybe we could run `git stash` after doing the `conda install` portion of the build. I noticed we also copy the GitHub repo into `/tmp` and keep it there, but could remove the source files from the container. 

We can also revisit #645 to see if we can figure out how to tag the releases.
