### ISSUE TITLE
error running: import plantcv.parallel

### ISSUE THREAD

**Issue by rodrign2002** [danforthcenter/plantcv#764]
**Describe the bug**
ImportError: cannot import name 'format_bytes' from 'dask.utils' (/Users/rodrign/anaconda3/lib/python3.7/site-packages/dask/utils.py)

I have the PCV version 3.12.0 and i am trying to create a workflow but I get an error with plantcv.parallel

**Comment by nfahlgren** [comment]
Hi @rodrign2002,

A few follow-up questions:

What procedure did you follow to install PlantCV?

Can you post the results of the command `conda list`?

**Comment by rodrign2002** [comment]
Thank you for your prompt reply
I struggled a lot for the installation... I tried a lot of ways but I don’t remember which one worked
Please see below  the results from conda list
<img width="968" alt="Screen Shot 2021-04-27 at 22 34 10" src="https://user-images.githubusercontent.com/83294535/116302046-658d4200-a7a9-11eb-83c8-4df84f99763b.png">

**Comment by dschneiderch** [comment]
you'll want to open the terminal since it looks like you are on a mac and then type
`conda list` 
make sure the prompt shows something like
`(base) /Users/rodrign` or better yet `(plantcv) /Useres/rodrign`

If you don't see the `(base)` trying typing `conda activate` first. To get `(plantcv)` use `conda activate plantcv`

**Comment by rodrign2002** [comment]
I uninstalled plantcv and installed it again and now it's working.. thank you :)

**Comment by nfahlgren** [comment]
Glad to hear it, thanks @rodrign2002! I will close this issue for now.
