### ISSUE TITLE
Camera settings and image information

### ISSUE THREAD

**Issue by rodrign2002** [danforthcenter/plantcv#765]
**Start a discussion about anything you would like**
Discussions can be used to ask questions, discuss new ideas, or anything else.
I am pretty new using the program, I read your article **A Versatile Phenotyping System and Analytics Platform Reveals Diverse Temporal Responses to Water Availability in Setaria** and I have some questions, I would appreciate it if you could guide me in my learning process.
1. Does the image resolution matter, I will take pictures of small plants using a photosimile, I will use two different cameras, does it matter or should I use the same configuration for all my pictures?
2. Which is a recommended picture resolution?
3. How to define in the code the camera settings: resolution, zoom, etc. Do I need a size marker in my image?
4. Can I take pictures in automatic shooting mode, or should I do it using the manual mode?
5. I found this on your home documentation website: Valid metadata that can be collected from filenames are camera, img type, zoom, exposure, gain, frame, lifter, timestamp, id, plant barcode, treatment, cartag, measurement label, and other. Should I include this information in each image so the program gets the information about my image characteristics and process the image accordingly? If that is the case what do camera, lifter and frame mean? 
6. I will take pictures before and after the treatment in a Photosimile, should I use the same instrument twice or can I use a small photosimile at the beginning of the experiment (easy to handle) and when my plants finish the treatment approximately 3 weeks later can I use the big photosimile to take the pictures or the instrument should be the same?
7. In the article you used the following formula to calculate the biomass: Mfw= 3.755 x 10ˆ-5 Asv-0.2704 where Mfw is fresh-weight biomass and Asv is side-view area. You used  the side-view area, the sum of the above-ground plant pixel area from all four side-view VIS images, because you were studying Setaria, in my case tomato plants have different architecture, should I use instead top view area as Asv?

I apologise for the excessive amount of questions, and I would really appreciate your help.

**Comment by nfahlgren** [comment]
Hi @rodrign2002,

Thank you for the questions, we are happy to help.

> 1. Does the image resolution matter, I will take pictures of small plants using a photosimile, I will use two different cameras, does it matter or should I use the same configuration for all my pictures?

Analysis can be easier if you use the same camera for an entire experiment (one less variable that changes). One of the issues with changing cameras, or the camera perspective/position relative to the plant, is that the real-world size a pixel represents changes. For example, in two images you might observe the plant is composed of 100 pixels, but if 1 pixel = 1mm in image 1 and 5mm in image 2, then the true projected area of each plant is different.

In the paper you mentioned, we used the same camera but changed the optical zoom settings throughout the experiment, which required us to determine a calibration curve for pixel size to correctly scale the data between camera settings. This could be done in your case by including markers in the background of your images that can be used for calibration.

> 2. Which is a recommended picture resolution?

The resolution really depends on your experiment and the type of detail you need. You would want a high enough resolution that you can see the structures you want to measure with more than just a few pixels. But on the other hand, I do not recommend excessively high resolution because it makes the computing time and memory requirements higher. I have generally had success working with data in the range of 5-12 MP, but I have also worked with lower and higher resolution data.

> 3. How to define in the code the camera settings: resolution, zoom, etc. Do I need a size marker in my image?

Including a size marker is a good idea, even if you do not end up using it.

> 4. Can I take pictures in automatic shooting mode, or should I do it using the manual mode?

Ideally, you want consistency between images. If automatic mode produces consistent results then it should work.

> 5. I found this on your home documentation website: Valid metadata that can be collected from filenames are camera, img type, zoom, exposure, gain, frame, lifter, timestamp, id, plant barcode, treatment, cartag, measurement label, and other. Should I include this information in each image so the program gets the information about my image characteristics and process the image accordingly? If that is the case what do camera, lifter and frame mean?

You should record information in the filenames (there are potentially other ways to do this but filenames are the most straightforward) that you want to keep track of for your experiment. The metadata are not all required but if they are included then they are included in the data output tables along with the measurements.

The metadata terms can be used somewhat flexibly, but our intended meanings are:

camera = camera name or identifier (i.e. what camera was used)

imgtype = type of image (e.g. RGB, NIR, Thermal, etc.) - Likely only important if your experiment includes multiple types of cameras

zoom, exposure, gain = camera settings (there could be many more potentially, we can always add more metadata terms if needed)

frame = an identifier to be used when collecting multiple images in a sequence. In our case we have a platform that rotates the plant and we take a picture at different angles, so frame is the angle of rotation. But it could be used in other contexts, or not used if there is only one image per plant per time point.

lifter = on our system the plant can be raised to different vertical positions, otherwise this term probably does not have a lot of other uses

timestamp = when the image was acquired. Often important to record to keep track of the order of images and/or the age of the plant.

id = an arbitrary identifier. It can be text, a number, or anything else that is useful to you (or omitted if not needed).

plantbarcode = a plant identifier

treatment = a treatment identifier

cartag = the identifier of a carrier in an automated facility

measurementlabel = an experiment identifier typically

other = any other information not accounted for in the terms above

When planning out your filenames keep in mind that it is easiest when there is a consistent delimiter between the metadata values (default = _) and that that delimiter is not used within a term (e.g. do not use an underscore within the timestamp if you also want to use it to split other terms). It is also best to have the same number of metadata terms used in each image filename.

> 6. I will take pictures before and after the treatment in a Photosimile, should I use the same instrument twice or can I use a small photosimile at the beginning of the experiment (easy to handle) and when my plants finish the treatment approximately 3 weeks later can I use the big photosimile to take the pictures or the instrument should be the same?

If you can use the same instrument the setup and analysis will be easier. But as addressed above, it is possible to calibrate the data (using size markers for example) so that data can be compared between the systems if it is better experimentally to use two.

> 7. In the article you used the following formula to calculate the biomass: Mfw= 3.755 x 10ˆ-5 Asv-0.2704 where Mfw is fresh-weight biomass and Asv is side-view area. You used the side-view area, the sum of the above-ground plant pixel area from all four side-view VIS images, because you were studying Setaria, in my case tomato plants have different architecture, should I use instead top view area as Asv?

It is definitely possible that top-view would produce a better biomass model for tomato but would require some experimentation to test.

I often do not convert from pixels to biomass anymore. In general, I have found that in most experiments the interest is in comparing relative responses as opposed to absolute differences, in which case comparing projected leaf area, height, or other digital measurements is often sufficient.

**Comment by rodrign2002** [comment]
Thank you so so much for your reply
