### ISSUE TITLE
When I was practicing Colorize Masks

### ISSUE THREAD

**Issue by Pepe-oss** [danforthcenter/plantcv#766]
**Describe the bug**
Sorry, I am a beginner of plantcv, or even a beginner of python. when I was practicing Colorize Masks, I ran into a problem. I really can’t understand why my computer can’t even allocate such a small amount of memory. 

**To Reproduce**
`masks = pcv.naive_bayes_classifier(img, pdf_file="naive_bayes_pdfs.txt")`
I have already trained, and then start to generate the mask

Then, this happened
`numpy.core._exceptions.MemoryError: Unable to allocate 183. MiB for an array with shape (4000, 6000) and data type float64`

**Expected behavior**
How can we continue to run？
Hope you can help me find a solution, thank you very much

**Local environment (please complete the following information):**
 - OS: windows 10
 - Environment： conda
 I'm pretty sure my computer has 16G of RAM

**Comment by nfahlgren** [comment]
Hi @Pepe-oss,

I agree, it does not look like there should be a memory limitation in your case. My hunch is that you might have installed the 32-bit version of Miniconda/Anaconda instead of the 64-bit version. It would not necessarily explain the memory allocation issue directly, because in a 32-bit program you can allocate up to 4GB of memory, but it may be related to how the program interacts with some system settings for allocating memory. There are a couple of Windows-specific responses to a similar question here: https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type.

I would start by checking the version of conda installed. If you start the program "Anaconda Prompt" and run `conda info` you should have output that has things like `win-64` or `x86_64` if it's the 64-bit version.

**Comment by Pepe-oss** [comment]
@nfahlgren ok，thanks! I will try
