### ISSUE TITLE
Readme enhancement

### ISSUE THREAD

**Issue by ericoporto** [danforthcenter/plantcv#80]
The first paragraph in a README should tell me what this project is, what it does, and placing some explanative image or linking a website could also help. Google linked me here when I was trying to find something to help me identify leaves.

**Comment by jshoyer** [comment]
Hi Érico,    thanks for the feedback. We can consider revising that paragraph and/or changing up the order of the readme.

We should definitely fix the broken link pointing to the former docs page (http://plantcv.danforthcenter.org/pages/documentation/). Changing the link to http://plantcv.readthedocs.io/ will be a quick fix. Maybe we can also get Jekyll to redirect, so that people who might stumble upon the old link in past versions of the readme do not see a 404 page.

If by "identify leaves" you mean segment leaves in images, you should definitely be able to use plantCV to do that, though the effort required will depend on the complexity of your application. If you want something to help you identify (e.g.) tree species based on smartphone photos you should probably look for dedicated apps for that purpose.
