### ISSUE TITLE
Tutorial: VIS/NIR Dual Image Workflow in Jupyter - get_nir troubleshooting

### ISSUE THREAD

**Issue by ivalethia** [danforthcenter/plantcv#804]
Hi,
I can't go any further in the tutorial after:
**The next step is to get the matching NIR image, resize, and place the VIS mask over it**
**In [21]:**
**nirpath = pcv.get_nir(path = "./", filename="NIR.jpg")**
**nir, path1, filename1 = pcv.readimage(nirpath, mode='gray')**

**# Inputs:**
**#   img - RGB or grayscale image to resize**
**#   factors - Resizing factors (width, height). E.g. (0.5, 0.5)**
**#   interpolation - Interpolation method. Available options are "auto" = select method automatically (default),**
**#   "area" = resampling using pixel area (OpenCV INTER_AREA), "bicubic" = bicubic interpolation (OpenCV INTER_CUBIC),**
**#   "bilinear" = bilinear interpolation (OpenCV INTER_LINEAR), "lanczos" = Lanczos interpolation (OpenCV**
**#   INTER_LANCZOS4), "nearest" = nearest-neighbor interpolation (OpenCV INTER_NEAREST).**
**nmask = pcv.transform.resize_factor(img=mask, factors=(0.28, 0.28))**

I got this error:

**Traceback (most recent call last):**
  **File "/home/ivalethia/Escritorio/NIR_VIS_workflow.py", line 176, in <module>**
    **nirpath = pcv.get_nir(path="./",filename="NIR_SV.jpg")**
  **File "/home/ivalethia/.local/lib/python3.8/site-packages/plantcv/plantcv/get_nir.py", line 49, in get_nir**
    **return nirpath**
**UnboundLocalError: local variable 'nirpath' referenced before assignment** 

I already tried to change the name of the file of the original VIS image file, the NIR image file, the path, the files inside the directory. 
As long as I can understand, the problem is that "get_nir" can't get the NIR image, but giving it the path and filename of the NIR image is not enough.
So, what I'm not seeing or missing? :(

*Also, would be useful a clear and extensive guide of naming parameters of images and any input file necessary to follow the tutorials.

Greetings, and I hope to watch another PhenomeForce Webinar with your team about developing NDVI or any "vegetation index applying" tutorial with NIR/VIS imaging!
Ivan Morales

**Comment by nfahlgren** [comment]
Hi @ivalethia,

Looking back at the `get_nir` function, it looks like there is an issue where it can return `nirpath` under some conditions before it is defined, which is the error you get. The function finds an NIR image that is paired with a VIS image, given the VIS image path and filename, but it was designed to expect filenames to be very specific to the phenotyping facility at the Danforth Center. So in its current form that function is not one I would recommend as a generalizable solution.

However, for following the tutorial with your own data, you could omit the `get_nir` step and directly input the NIR image filepath to `readimage`:

```python
nir, path1, filename1 = pcv.readimage("./NIR.jpg", mode='gray')
```

We are working on updates to the parallel subpackage in PlantCV that will allow images to be grouped into sets for analysis. I would envision that we would change the VIS/NIR tutorial in the future based on that type of grouping rather than using `get_nir`.

We also need to update the tutorial soon with some of the new tools we have for image fusion such as `pcv.transform.warp` and `pcv.image_fusion`. In your context, these can be used to calculate NDVI: https://plantcv.readthedocs.io/en/latest/image_fusion/

**Comment by ivalethia** [comment]
Hi Noah (@nfahlgren),
Thanks for such clear and fast answer, it worked after I followed your comments.
Now I'm planning to do "Multiplant" and "Hyperspectral" tutorials, to finally try a multiplant NDVI experiment (all these by my own, no lab or institute work). Do you think I could reach reproducible testing and data with these three tutorials plus the pcv.transform.warp and pcv.image_fusion tools?
If you are wondering, I'm using a Raspberry Pi 4 (8GB), Raspberry Pi OS (2021-05-07 release), a camera module V1 (5MP OV5647) with a filter switch (like this: https://www.amazon.es/gp/product/B07VW7ZKQY/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) (changed the no-filter glass with a  piece of exposed and developed Canon film) and IR leds (these: https://www.amazon.es/gp/product/B07SKF1K87/ref=ppx_yo_dt_b_asin_title_o07_s01?ie=UTF8&psc=1).
Images are obtained by Picamera Code in DNG and JPG formats (maybe should I to transform them to ' planar BGR' with the openCV plugin or any other unencoded format?), this a part of the code:
        *GPIO.setup(21, GPIO.OUT)*
        *GPIO.output(21, GPIO.HIGH) #SWITCHING TO VIS FILTER, WITHOUT IR WAVLENGHTS*
        *print ("VIS Mode ON: "+str(i))*
        *camera.resolution = (2592, 1944)*
        *shutter_speed = 8*
        *exposure_speed = 8*
        *analog_gain = 2/1*
        *digital_gain = 2/1*
        *awb_mode = 'off'*
        *awb_gains = 1*
        *iso = 100*
        *exposure_mode = 'off'*
        *camera.start_preview()*
        *sleep(2)*
        *camera.capture('TIMELAPSE/VIS'+ str(i) +'.jpg', bayer=True)*
        *d.convert('TIMELAPSE/VIS'+ str(i) +'.jpg') #OBTAINING .DNG FILES*
        *GPIO.setup(21, GPIO.OUT)*
        *GPIO.output(21, GPIO.LOW) #SWITCHING TO IR FILTER (EXPOSED FILM), WITHOUT VIS WAVLENGHTS*
        *print ("IR Mode ON: "+str(i))*
        *camera.resolution = (2592, 1944)*
        *shutter_speed = 8*
        *exposure_speed= 8*
        *analog_gain = 2/1*
        *digital_gain = 2/1*
        *awb_mode = 'off'*
        *awb_gains = 1*
        *iso = 100*
        *exposure_mode = 'off'*
        *camera.start_preview()*
        *sleep(2)*
        *camera.capture("TIMELAPSE/NIR"+ str(i) +".jpg", bayer=True)*
        *d.convert('TIMELAPSE/NIR'+ str(i) +'.jpg') #OBTAINING .DNG FILES FROM*

Hope to hear about you soon, greetings.
Ivan Morales.
