### ISSUE TITLE
What happen when I run the "plantcv-shoot-phenotyping"third command in jupter notebook 

### ISSUE THREAD

**Issue by moya1507** [danforthcenter/plantcv#805]
![image](https://user-images.githubusercontent.com/87818922/126657144-e8c28328-c10f-41e8-92ed-2ef01dfd4846.png)

**Comment by nfahlgren** [comment]
Hi @moya1507,

This notebook is from the `plantcv-tutorials` materials (https://github.com/danforthcenter/plantcv-workshop) correct? This notebook assumes that you run the notebook from the `plantcv-tutorials` directory. If you are running it from somewhere else you might need to adjust the path to the input image on your computer: `plantcv-tutorials\examples\shoot-images\VIS_SV_0_z2500_h2_g0_e82_180256.png`

The `plantcv-tutorials` materials are likely somewhat out of date because we have used them for past workshops, so alternatively you might find the interactive tutorials we maintain more useful. They can be accessed from the documentation here, https://plantcv.readthedocs.io/en/stable/, by clicking on the "launch binder" button under the Tutorials heading. The notebook that opens by default has a table of contents to the individual tutorials contained in this cloud computing environment.
