### ISSUE TITLE
Color Correction Analysis

### ISSUE THREAD

**Issue by EdwinP503** [danforthcenter/plantcv#879]
Hello,

I am working on extracting data from a collection of images from 1998/99, and I was planning on applying a color correction to them because their hue values are very diverse across all images. Following the color correction tutorial I created a color mask and tried to apply Scenario A for one target image and one source image.

The zoom and color checker position are not the same for most images so I wanted to ask what way does color correction works on images and if you guys have any suggestion for how I can approach the objective.

The color mask I wanted to select included the 3 color stickers and the white image label.  

![98x0057](https://user-images.githubusercontent.com/73755937/157482769-7a61d90e-7886-4018-8fe4-3e2a5becca29.jpg)

![98x0137](https://user-images.githubusercontent.com/73755937/157483231-5533a392-c368-4318-bc4a-affae915b7f8.jpg)

I'd appreciate any help

Thank you!

**Comment by nfahlgren** [comment]
Hi @EdwinP503!

One thing I can say is that when we tested the color correction method built into PlantCV currently we tested dropping out color chips from our color cards to see what the minimum number of data points it would support. My recollection is that we could only get down to 7-8 color chips (starting from 24) before it failed. I think that's probably because we use the average values per chip, so we're only building a model with 7-8 data points.

@JorgeGtz has recently been putting some thought into color correction and one of the things I know he's been thinking about is using more individual pixel data points for each color reference. That might help with the minimum color reference problem. What do you think Jorge?

The one other thing I can suggest is using using the `report_size_marker` function to measure the size of one or all of the RGB color tags, you can use this value downstream to normalize any size measurements to account for differences in field of view.

**Comment by JorgeGtz** [comment]
Hi,

As @nfahlgren mentions, I don't think the model is well suited for using so few color references. I tried using multiple points for each color reference but the results are not consistent. 

An option is to try `white_balance` with an ROI in the white label and see if that helps obtaining more uniform results.

**Comment by EdwinP503** [comment]
Thanks for the input @nfahlgren, I did managed to extract only the red sticker size for all the images using the `find object` and `analyze object` functions after creating a mask using the "a" colorspace and a binary threshold. However, I am not familiar with how I can use them to normalize size measurements.

@JorgeGtz would there be a significant difference in using either mode `hist` or `max` with the ROI on the label?

**Comment by EdwinP503** [comment]
Sorry for the late response, thank you for the input!
