### ISSUE TITLE
More color depth support needed

### ISSUE THREAD

**Issue by Clarivy** [danforthcenter/plantcv#883]
Hi! 
I'm using plantcv.transform.correct_color to match two color checkers. But I'm having some issues. 
The images in my project are in 16-bit color depth which is not supported according to your source code. The outcome images are incorrect.

I checked the source code. And I found some snippets like this:

```python
    # convert img to float to avoid integer overflow, normalize between 0-1
    source_img = source_img.astype(np.float64)/255
```

To support deeper color depth, you should check whether img.dtype is numpy.uint8, numpy.uint16 or numpy.float32. And divide img by different value.

**Comment by nfahlgren** [comment]
Hi @Clarivy, @JorgeGtz has worked on implementing this in the color correction module in #885. It works but we realized that there are going to be bigger issues if you were planning on using the corrected images with other PlantCV modules.

The two main issues we know about are 1) that `matplotlib`, which we use for displaying images, clips 16-bit data to 8-bit, so the images are not displayed correctly; and 2) that OpenCV does not support 16-bit color images.

A couple things we discussed:
* If you just need color correction and do not plan on using other PlantCV functions, then I think we could accept the changes in #885 because they wouldn't affect our standard functionality but would allow you to use color correction on your data.
* If you were planning on utilizing PlantCV, then I think your data would need to be converted to 8-bit. We discussed the potential need for a new function that would correctly scale the data from one data type to another that could be useful in this case.

Please let us know your thoughts, thanks!

**Comment by Clarivy** [comment]
Thank you for your rapid reply.

I am only using the color correction module currently. Higher precision is really important to me, so the implementation is really helpful :)

**Comment by nfahlgren** [comment]
Thanks @Clarivy, PR #885 introduces these changes and we just merged them into the main branch.

**Comment by nfahlgren** [comment]
We also added this update to the release v3.14, which is now available on PyPI. It should also be available through conda within a day or so.
