### ISSUE TITLE
sample_images filtering

### ISSUE THREAD

**Issue by kmurphy61** [danforthcenter/plantcv#923]
I would like to use the sample_images function (`plantcv-utils.py sample_images`) to create a new folder with a random sampling of my images to test a parallelized workflow. However, my folders contain many images - top view, side view, near infrared, etc - and the function cannot filter or pattern match to only sample the top view images. Can a filter be added to the function? Thank you!

**Comment by nfahlgren** [comment]
Hi @kmurphy61, good catch. In the `4.x` branch, we updated the `parallel` module to handle the new LemnaTec system download tool from https://github.com/danforthcenter/data-science-tools. We updated several other components of PlantCV that intersected with handling datasets but did not update the [sample_images](https://github.com/danforthcenter/plantcv/blob/master/plantcv/utils/sample_images.py) module.

So the main issue is that it treats your dataset like "just" a directory of images and randomly samples them, resulting in you getting a jumble of all types. The intention of the module with data from the LemnaTec system is that it randomly samples snapshots and replicates the input data structure, but since it doesn't know about the new dataset format it doesn't work as intended.

We will look into two potential fixes. The quick fix is we look at the dataset like this:

```python
# This is an old "phenofront" dataset format
if os.path.exists(os.path.join(source_path, 'SnapshotInfo.csv')):
```

And we could just add in another else if:

```python
# New dataset format
elif os.path.exists(os.path.join(source_path, 'metadata.json')):
```

But there might be a cleaner way to do this with some of the new pieces in the parallel metadata_parser module.
