### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by rodrign2002** [danforthcenter/plantcv#965]
Hi everyone,

I have the following problem, I have created a plantcv workflow previously and it worked. Recently it stopped working, and I am getting the error

 - distributed.client - ERROR - 
ConnectionRefusedError: [Errno 61] Connection refused

I was following this tutorial:

https://plantcv.readthedocs.io/en/stable/tutorials/vis_tutorial/

and converted the jupyter notebook into a workflow script. Then I run with

plantcv-workflow.py --config test.json

where the test.json file is referencing the workflow script.

My Local environment:
 - OS: macOS Big Sur Version 11.6.4
 - Environment: conda
 - PlantCV Version 3.14.1

I don't remember which version I used to create the jupyter notebook and workflow script, but it was probably about one year ago with the then-current version from conda.

Another related problem: I cannot find any information on the web page anymore on how to convert jupyter notebooks into workflow scripts.

**Comment by nfahlgren** [comment]
Hi @rodrign2002, the documentation for converting from Jupyter to a workflow script is on this page: https://plantcv.readthedocs.io/en/stable/jupyter/

The distributed.client error may not actually indicate that your workflow didn't work - can you confirm you did not get the results you expected?

We have noticed an increase scary sounding errors from the parallelization system (Dask) - but in many cases they occur when the cluster shuts down and don't affect PlantCV. As a side note, we're building a release for PlantCV v4 that will address this issue.

**Comment by nfahlgren** [comment]
Hi @theusst, no worries at all! There are a lot of docs, which is good, but also somewhat of a needle in a haystack.

And the errors indeed sound alarming and we have gotten a lot of questions about them because they definitely imply that it's not working. But I believe that in all cases I have looked at the errors are not fatal for the actual data processing and only occurs when we shutdown the Dask cluster (whether LocalCluster or one of the distributed clusters). In #958 I think we fixed this issue and it will be part of the v4.0 release that's upcoming.

For now, I think the errors are safe to ignore as long as the results file (and exported CSV files) contain data. Your configuration definitely looks good to me.

Thanks!
