### ISSUE TITLE
Skeletonize function

### ISSUE THREAD

**Issue by mserouar** [danforthcenter/plantcv#990]
Hi !

I'm trying to use the skeleton function, while correcting the flaws in my binarisation as follows : 

```
img = cv2.morphologyEx(img, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3,3)))
img = cv2.morphologyEx(img, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (19,19)))
img = cv2.dilate(img, None, iterations=15)

```

Here are the results : 
![image](https://user-images.githubusercontent.com/57948061/208050379-0e69e513-061f-42ca-b598-eee0420dd407.png)

This is a pretty good mask, however the skeletonize function tends to render really bad outputs : 

![image](https://user-images.githubusercontent.com/57948061/208050887-359dcba6-cc28-4b08-b549-9b3aa66a174a.png)

Is there a known trick to bypass this issue ? 
Thanks a lot !

**Comment by HaleySchuhl** [comment]
Hi @mserouar thanks for opening this issue!

Skeletons preserve all structure within a binary mask, so (unfortunately) the plant mask needs to be perfectly combined as any disconnected plant tissue will remain separate. This might mean using dilation even more aggressively to connect your mask. Or lowering your initial threshold (include more plant & noise) and use functions to clean up non-plant material afterwards. Some of the most common include region of interest tools and filters for cleaning objects by size. 

Also, I always recommend `pcv.fill_holes` since any gap regardless of size will break the sorting algorithm. Finally, if you are using Jupyter notebooks, you can use `%matplotlib notebook` to turn on interactive notebooks. Skeletons are always one pixel wide, and imgs with high resolution like yours can end up appearing incomplete, but zooming in SUPER close should show that there's a pixel-wide skeleton for all part of your binary mask.

**Comment by mserouar** [comment]
Hi and thanks for this quick answer ! 

I already preprocessed much on it (no need of  pcv.fill_holes of dilate more as you said.)
This is definitely a notebook render issue coupled with the single pixel width of skeleton and large images.

Thanks again !
 
![image](https://user-images.githubusercontent.com/57948061/208365011-e03b9259-d6b8-4b94-83a0-13a5f7c2199e.png)
